Repository Neufund/platform-frontend, pull requests merged in 2019-06, with the labels that each got.

#3058 #2877 money formatters investment modal
  app/components/eto/dashboard/bookBuildingWidget/BookBuildingWidget.stories.tsx
  app/components/eto/dashboard/bookBuildingWidget/BookBuildingWidget.tsx
  app/components/eto/dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.stories.tsx
  app/components/eto/dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.tsx
  app/components/modals/tx-sender/investment-flow/Investment.tsx
  app/components/modals/tx-sender/investment-flow/InvestmentTypeSelector.tsx
  app/components/modals/tx-sender/investment-flow/utils.tsx
  app/components/shared/DatePicker.tsx
  app/components/shared/TimeLeft.unsafe.tsx
  app/components/shared/forms/index.tsx
  app/modules/eto-flow/sagas.ts
  intl/locales/en-en.json
Labels: QA

#3020 upper cases jurisdiction from backend
  app/components/eto/overview/EtoOverviewThumbnail/Cover.tsx
  app/lib/api/eto/EtoApi.ts
  app/modules/eto/sagas.ts
  app/modules/eto/utils.spec.ts
  app/modules/eto/utils.ts
  app/test-e2e/investor-dashboard/LightWalletInvestorDashboard.spec.e2e.io.ts
  test/fixtures.ts
Labels: TECH

#3029 #2921 Add color generator to shareholders chart
  app/components/eto/public-view/LegalInformationWidget.stories.tsx
  app/components/eto/public-view/LegalInformationWidget.tsx
  app/components/shared/charts/utils.ts
  app/lib/api/eto/EtoApi.interfaces.unsafe.tsx
Labels: QA

#3071 sets mime type of tos to pdf
  app/modules/terms-of-service-modal/sagas.ts
  app/test-e2e/bank-transfer/RedeemNEUR.spec.e2e.ts
  app/test-e2e/eto-view/EtoViewForInvestor.spec.e2e.io.ts
Labels: Bug

#3065 #2877 money formatters in wallet
  app/components/modals/icbm-wallet-balance-modal/BalanceModal.tsx
  app/components/modals/icbm-wallet-balance-modal/IcbmWalletBalanceModal.stories.tsx
  app/components/shared/formatters/Money.stories.tsx
  app/components/shared/formatters/Money.tsx
  app/components/wallet-selector/ledger/WalletLedgerChooserComponent.stories.tsx
  app/components/wallet-selector/ledger/WalletLedgerChooserTableAdvanced.tsx
  app/components/wallet-selector/ledger/WalletLedgerChooserTableSimple.tsx
  app/components/wallet/TotalEuro.module.scss
  app/components/wallet/TotalEuro.tsx
  app/components/wallet/transaction-list/TransactionList.unsafe.tsx
  app/components/wallet/wallet-balance/WalletBalance.tsx
  app/test-e2e/wallets/WalletMigrate.spec.e2e.ts
  intl/locales/en-en.json
Labels: QA

#3077 #3075 Fix bad formatting of investment cards
  app/components/dashboard/eto-list/EtoList.tsx
  app/components/eto/overview/EtoOverviewStatus/CounterWidget.module.scss
  app/components/eto/overview/EtoOverviewThumbnail/Cover.tsx
  app/components/eto/overview/EtoOverviewThumbnail/EtoCardPanel.module.scss
  app/components/eto/overview/EtoOverviewThumbnail/EtoCardPanel.tsx
  app/components/eto/overview/EtoOverviewThumbnail/EtoOverviewThumbnail.tsx
  app/components/eto/overview/EtoOverviewThumbnail/EtosComingSoonThumbnail.module.scss
  app/components/eto/overview/EtoOverviewThumbnail/EtosComingSoonThumbnail.stories.tsx
  app/components/eto/overview/EtoOverviewThumbnail/EtosComingSoonThumbnail.tsx
  app/components/eto/public-view/Cover.module.scss
  app/components/eto/public-view/Cover.tsx
  app/components/landing/EtoOfferingCard.tsx
  app/components/shared/ResponsiveImage.module.scss
  app/components/shared/ResponsiveImage.tsx
Labels: Bug, QA

#3072 Dispatch correct action on product change
  app/modules/eto-flow/reducer.ts
  app/modules/eto-flow/sagas.ts
Labels: Bug, QA

#3079 At/#3078 set eto date calender widget bug
  app/components/shared/DatePicker.tsx
  app/components/shared/forms/fields/FormFieldDatePicker.stories.tsx
  app/components/shared/forms/fields/FormFieldDatePicker.unsafe.tsx
Labels: QA

#3088 Make E2E tests Regid
  app/test-e2e/bank-transfer/RedeemNEUR.spec.e2e.io.ts
Labels: TECH

#2998 #2980 - Rearrange ETO Dashboard
  app/components/eto/EtoDashboard.module.scss
  app/components/eto/EtoDashboard.stories.tsx
  app/components/eto/EtoDashboard.tsx
  app/components/eto/shared/ETOState.module.scss
  app/components/eto/shared/ETOState.tsx
  app/components/eto/utils.spec.ts
  app/components/eto/utils.ts
  app/components/shared/Heading.module.scss
  app/components/shared/Heading.tsx
  app/test-e2e/eto-registration/EtoRegistrationUtils.ts
  intl/locales/en-en.json
Labels: QA

#3097 Add easy way to connect to VM backend
  app/config/.env.common
  package.json
  webpack/proxy-urls.js
  webpack/webpack.config.dev.js
Labels: TECH

#3060 #2877 money formatters in tx-sender
  app/components/modals/tx-sender/investor-payout/AcceptTransactionDetails.tsx
  app/components/modals/tx-sender/investor-payout/RedistributeTransactionDetails.tsx
  app/components/modals/tx-sender/redeem/BankTransferRedeemDetails.tsx
  app/components/modals/tx-sender/unlock-wallet-flow/UnlockWalletTransactionDetails.tsx
  app/components/modals/tx-sender/upgrade-flow/UpgradeTransactionDetails.unsafe.tsx
  app/components/modals/tx-sender/user-claim/ClaimTransactionDetails.tsx
  app/components/modals/tx-sender/withdraw-flow/WithdrawTransactionDetails.tsx
Labels: QA

#3099 Remove unused `get-params` dependency
  package.json
  yarn.lock
Labels: TECH

#3098 Fix flaky change email test
  app/components/layouts/LayoutAuthorized.tsx
  app/components/layouts/LayoutAuthorizedMenu.spec.tsx
  app/components/layouts/LayoutAuthorizedMenu.stories.tsx
  app/components/layouts/LayoutAuthorizedMenu.tsx
  app/components/modals/accept-tos-modal/AcceptTosModal.tsx
  app/test-e2e/1.long-e2e-tests/2.ChangeEmail.spec.e2e.io.ts
  app/test-e2e/link-triggered-flows/WalletVerify.spec.e2e.io.ts
  app/test-e2e/register/LightWalletETOLogin.spec.e2e.io.ts
  app/test-e2e/routing/RegisterRedirectIfNoVerifiedEmail.spec.e2e.io.ts
  app/test-e2e/settings/BackupSeed.spec.e2e.io.ts
  app/test-e2e/settings/LightWalletRegister.spec.e2e.io.ts
  app/test-e2e/settings/VerifyEmailWidget.spec.e2e.io.ts
  app/test-e2e/utils/index.ts
  app/test-e2e/wallets/WalletRecover.spec.e2e.io.ts
Labels: TECH

#3083 #2320 move formatted message out of interfaces
  app/components/shared/formatters/FormatShortNumber.spec.tsx
  app/components/shared/formatters/FormatShortNumber.tsx
  app/components/shared/formatters/Money.spec.tsx
  app/components/shared/formatters/Money.tsx
  app/components/shared/formatters/MoneyRange.tsx
  app/components/shared/formatters/utils.ts
  app/components/translatedMessages/messages.tsx
  app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  app/lib/api/eto/EtoPledgeApi.interfaces.unsafe.ts
  app/lib/api/eto/EtoPledgeApi.interfaces.unsafe.tsx
  app/lib/api/util/schemaHelpers.unsafe.ts
  app/test-e2e/utils/index.ts
Labels: TECH

#3090 number of investors fix
  app/components/eto/overview/EtoOverviewStatus/EtoMaxCapExceeded.tsx
  app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentWidget.tsx
  app/components/eto/overview/EtoOverviewThumbnail/InvestmentStatus/InvestmentStatus.spec.tsx
  app/components/eto/overview/EtoOverviewThumbnail/InvestmentStatus/InvestmentStatus.tsx
  app/components/shared/formatters/utils.spec.ts
  app/test-e2e/investor-dashboard/LightWalletInvestorDashboard.spec.e2e.io.ts
  app/types.d.ts
  intl/locales/en-en.json
Labels: QA

#3066 Adds automatic Backend Contract SHA generation
  .circleci/config.yml
  .prettierignore
  README.md
  app/test-e2e/bank-transfer/RedeemNEUR.spec.e2e.io.ts
  app/test-e2e/eto/InvestWithNEur.spec.e2e.ts
  e2e/run-backend.js
  e2e/run_backend.sh
  e2e/setup-e2e.sh
  health-check-sha.json
  package.json
  patches/bitcore-mnemonic+8.3.3.patch
  scripts/getShasFromHealthCheck.js
Labels: TECH

#3069 #2877 money formatters in bank flow
  app/components/eto/overview/EtoOverviewThumbnail/EtoOverviewThumbnail.stories.tsx
  app/components/modals/bank-transfer-flow/purchase/BankTransferPurchaseSummary.tsx
  app/components/modals/bank-transfer-flow/verify/BankTransferVerifyAgreement.tsx
  app/components/modals/bank-transfer-flow/verify/BankTransferVerifySummary.tsx
  app/components/modals/tx-sender/redeem/BankTransferRedeemInit.tsx
  app/components/modals/tx-sender/user-claim/Summary.stories.tsx
  app/components/portfolio/AssetPortfolio.tsx
  app/components/portfolio/PortfolioMyAssets.tsx
  app/components/portfolio/PortfolioPastInvestments.stories.tsx
  app/components/portfolio/PortfolioPastInvestments.tsx
  app/components/portfolio/PortfolioReservedAssets.tsx
  app/components/shared/InvestmentPreview.tsx
  app/modules/investor-portfolio/selectors.ts
  app/modules/investor-portfolio/types.ts
  app/modules/investor-portfolio/utils.ts
  app/test-e2e/bank-transfer/BankVerification.spec.e2e.ts
  app/test-e2e/bank-transfer/Purchase.spec.e2e.ts
Labels: QA

#3112 Splits FullEtoRegistration into smaller tests for memory optimization
  .circleci/config.yml
  app/test-e2e/1.long-e2e-tests/1.FullEtoRegistrationAndSubmit.spec.e2e.io.ts
Labels: TECH

#3128 Remove unused variable from EtoState
  app/components/eto/shared/ETOState.tsx
Labels: TECH

#3133 #3016 Fix hot reloading
  app/utils/OnEnterAction.tsx
  package.json
  yarn.lock
Labels: TECH

#3114 investment summary number formatters
  app/components/eto/shared/EtoView.tsx
  app/components/modals/tx-sender/TxSender.tsx
  app/components/modals/tx-sender/investment-flow/InvestmentTransactionDetails.spec.tsx
  app/components/modals/tx-sender/investment-flow/InvestmentTransactionDetails.tsx
  app/components/modals/tx-sender/investment-flow/Summary.stories.tsx
  app/components/modals/tx-sender/investment-flow/Summary.tsx
  app/components/modals/tx-sender/investment-flow/utils.tsx
  app/components/shared/Money.module.scss
  app/components/shared/Money.spec.tsx
  app/components/shared/Money.stories.tsx
  app/components/shared/Money.unsafe.tsx
  app/components/shared/formatters/FormatNumber.tsx
  app/test-e2e/eto/InvestChange.spec.e2e.ts
  intl/locales/en-en.json
Labels: QA

#3137 Adds retry on run backend fail
  e2e/run-backend.js
  health-check-sha.json
Labels: TECH

#3148 Update crypto-random-string
  @types/crypto-random-string/index.d.ts
  app/di/setupBindings.ts
  app/lib/dependencies/cryptoRandomString.ts
  app/modules/auth/jwt/sagas.ts
  health-check-sha.json
  package.json
  test/integrationTestUtils.unsafe.tsx
  yarn.lock
Labels: TECH

#3150 Refactor auth, bookbuilding-flow, contracts, eto-documents and eto-flow modules to use new action creator
  app/modules/auth/actions.ts
  app/modules/auth/reducer.ts
  app/modules/auth/sagas.ts
  app/modules/auth/user/sagas.ts
  app/modules/bookbuilding-flow/actions.ts
  app/modules/bookbuilding-flow/reducer.ts
  app/modules/bookbuilding-flow/sagas.ts
  app/modules/contracts/actions.ts
  app/modules/contracts/reducer.ts
  app/modules/deposit-eth-modal/actions.ts
  app/modules/eto-documents/actions.ts
  app/modules/eto-documents/reducer.ts
  app/modules/eto-documents/sagas.ts
  app/modules/eto-flow/actions.ts
  app/modules/eto-flow/reducer.ts
  app/modules/eto-flow/sagas.ts
  app/modules/sagas.ts
  app/modules/terms-of-service-modal/sagas.ts
  app/modules/tx/monitor/sagas.ts
  app/modules/wallet/sagas.ts
  app/store.ts
  health-check-sha.json
  yarn.lock
Labels: TECH

#3116 #3102 - Eto documents changes
  app/components/documents/Documents.module.scss
  app/components/documents/Documents.tsx
  app/components/documents/utils.tsx
  intl/locales/en-en.json
Labels: QA

#3155 #3145 Change rounding of short number forms
  app/components/shared/formatters/FormatNumberRange.spec.tsx
  app/components/shared/formatters/FormatShortNumber.spec.tsx
  app/components/shared/formatters/FormatShortNumber.tsx
  app/components/shared/formatters/Money.spec.tsx
  app/components/shared/formatters/Money.tsx
  app/data/etoCompanies.ts
Labels: QA

#3147 #3100 Mark date as obligatory field
  app/components/eto/overview/EtoOverviewStatus/CampaigningWidget/CampaigningActivatedInvestorApprovedWidgetLayout.tsx
  app/components/eto/registration/pages/EtoTerms.tsx
  app/components/eto/registration/pages/InvestmentTerms.tsx
  app/components/eto/registration/pages/LegalInformation.tsx
  app/components/shared/MaskedNumberInput.tsx
  app/components/shared/forms/fields/FormCategoryDistribution.unsafe.tsx
  app/components/shared/forms/fields/FormField.tsx
  app/components/shared/forms/fields/FormFieldDate.module.scss
  app/components/shared/forms/fields/FormFieldDate.stories.tsx
  app/components/shared/forms/fields/FormFieldDate.tsx
  app/components/shared/forms/fields/FormFieldDate.unsafe.tsx
  app/components/shared/forms/fields/FormFieldRaw.stories.tsx
  app/components/shared/forms/fields/FormInput.tsx
  app/components/shared/forms/fields/FormMaskedInput.stories.tsx
  app/components/shared/forms/fields/FormMaskedInput.tsx
  app/components/shared/forms/fields/FormMaskedNumberInput.tsx
  app/components/shared/forms/fields/NumberTransformingField.stories.tsx
  app/components/shared/forms/fields/NumberTransformingField.tsx
  app/components/shared/forms/index.tsx
  app/components/shared/forms/layouts/FormFieldLayout.stories.tsx
  app/components/shared/forms/layouts/FormFieldLayout.tsx
  app/components/shared/forms/layouts/InputLayout.spec.tsx
  app/components/shared/forms/layouts/InputLayout.tsx
  app/types.d.ts
  intl/locales/en-en.json
Labels: QA
