Repository Neufund/platform-frontend, pull requests merged in 2019-11, with the labels that each got.

#3534 First steps into a gasless platform
  packages/web/app/components/modals/tx-sender/shared/TxError.stories.tsx
  packages/web/app/config/.env.commit
  packages/web/app/config/.env.common
  packages/web/app/config/.env.e2e
  packages/web/app/config/getConfig.ts
  packages/web/app/lib/api/users/UsersApi.ts
  packages/web/app/lib/api/users/interfaces.ts
  packages/web/app/lib/web3/constants.ts
  packages/web/app/lib/web3/ledger-wallet/LedgerConnector.ts
  packages/web/app/lib/web3/ledger-wallet/ledgerUtils.ts
  packages/web/app/lib/web3/light-wallet/LightWallet.ts
  packages/web/app/lib/web3/types.ts
  packages/web/app/modules/tx/event-channel/errors.ts
  packages/web/app/modules/tx/event-channel/sagas.ts
  packages/web/app/modules/tx/event-channel/types.ts
  packages/web/app/modules/tx/monitor/sagas.ts
  packages/web/app/modules/tx/sender/sagas.ts
  packages/web/app/modules/tx/transactions/investment/sagas.ts
  packages/web/app/modules/tx/validator/constants.ts
  packages/web/app/modules/tx/validator/sagas.ts
  packages/web/app/modules/tx/validator/withdraw/sagas.ts
  packages/web/app/test-e2e/eto/InvestWithNoMoney.spec.e2e.io.ts
  packages/web/app/test-e2e/eto/InvestWithNoMoney.spec.e2e.ts
  packages/web/app/test-e2e/pending-transactions/SupportForPendingTransactionsDuringTxFlow.spec.e2e.ts
  packages/web/app/test-e2e/pending-transactions/SupportForPendingTransactionsInHeader.spec.e2e.ts
  packages/web/app/test-e2e/pending-transactions/generalPendingTxFixture.ts
  packages/web/app/test-e2e/utils/assertions.ts
  packages/web/app/test-e2e/utils/index.ts
  packages/web/app/test-e2e/utils/userHelpers.ts
  packages/web/app/test-e2e/wallets/WalletWithdraw.spec.e2e.ts
  packages/web/app/utils/opaque-types/utils.ts
  packages/web/health-check-sha.json
  packages/web/test/fixtures.ts
Labels: QA

#3690 #3667 Countdown layout change
  packages/web/app/components/eto/overview/EtoOverviewStatus/CounterWidget.module.scss
  packages/web/app/components/eto/overview/EtoOverviewStatus/CounterWidget.tsx
  packages/web/app/components/shared/Counter.module.scss
  packages/web/intl/locales/en-en.json
Labels: QA

#3660 #3519 KYC changes for US investors
  packages/web/app/components/eto/shared/EtoAddDocument.module.scss
  packages/web/app/components/eto/shared/EtoAddDocument.tsx
  packages/web/app/components/kyc/KYCprocess.stories.tsx
  packages/web/app/components/kyc/business/BeneficialOwner.unsafe.tsx
  packages/web/app/components/kyc/business/BusinessData.unsafe.tsx
  packages/web/app/components/kyc/business/LegalRepresentative.unsafe.tsx
  packages/web/app/components/kyc/personal/Start.unsafe.tsx
  packages/web/app/components/kyc/shared/AddDocuments.tsx
  packages/web/app/components/shared/Document.module.scss
  packages/web/app/components/shared/Document.tsx
  packages/web/app/components/shared/DocumentUploadable.tsx
  packages/web/app/components/shared/Dropzone.module.scss
  packages/web/app/components/shared/Dropzone.stories.tsx
  packages/web/app/components/shared/Dropzone.tsx
  packages/web/app/components/shared/MultiFileUpload.module.scss
  packages/web/app/components/shared/MultiFileUpload.tsx
  packages/web/app/components/shared/UploadedFiles.module.scss
  packages/web/app/components/shared/UploadedFiles.tsx
  packages/web/app/components/shared/forms/fields/FormFieldLabel.tsx
  packages/web/app/components/shared/forms/fields/FormSelectStateField.unsafe.tsx
  packages/web/app/components/shared/forms/fields/utils.unsafe.tsx
  packages/web/app/components/shared/loading-indicator/LoadingIndicator.module.scss
  packages/web/app/components/shared/loading-indicator/LoadingIndicator.stories.tsx
  packages/web/app/components/shared/loading-indicator/LoadingIndicator.tsx
  packages/web/app/components/shared/notification-widget/Notification.spec.tsx
  packages/web/app/components/shared/notification-widget/Notification.stories.tsx
  packages/web/app/components/shared/notification-widget/Notification.tsx
  packages/web/app/components/shared/notification-widget/NotificationWidget.tsx
  packages/web/app/components/wallet-selector/WalletSelectorLayout.tsx
  packages/web/app/config/.env.commit
  packages/web/app/config/externalRoutes.ts
  packages/web/app/lib/api/kyc/KycApi.interfaces.ts
  packages/web/app/lib/api/kyc/KycApi.ts
  packages/web/app/modules/kyc/actions.ts
  packages/web/app/modules/kyc/reducer.ts
  packages/web/app/modules/kyc/sagas.ts
  packages/web/app/modules/notifications/actions.ts
  packages/web/app/modules/notifications/reducer.spec.ts
  packages/web/app/modules/notifications/reducer.ts
  packages/web/app/modules/notifications/selectors.ts
  packages/web/app/modules/notifications/types.ts
  packages/web/app/styles/mixins/typography.scss
  packages/web/app/test-e2e/kyc/KYCFlowIndividualIDnow.spec.e2e.io.ts
  packages/web/app/test-e2e/kyc/KYCFlowIndividualManual.spec.e2e.io.ts
  packages/web/app/test-e2e/kyc/KYCFlowIndividualOutsourced.spec.e2e.io.ts
  packages/web/app/test-e2e/kyc/fixtures.ts
  packages/web/app/utils/StringUtils.spec.ts
  packages/web/app/utils/StringUtils.ts
  packages/web/app/utils/yupUtils.ts
  packages/web/intl/locales/en-en.json
Labels: QA

#3694 #3520 Block investing for US investors
  packages/web/app/components/eto/overview/EtoOverviewStatus/CampaigningWidget/RegisterNowWidget.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentWidget.stories.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentWidget.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/USInvestorMessage.stories.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/USInvestorMessage.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/Message.module.scss
  packages/web/app/components/eto/overview/EtoOverviewStatus/Message.tsx
  packages/web/app/lib/api/util/customSchemas.ts
  packages/web/app/modules/auth/selectors.ts
  packages/web/app/modules/eto/selectors.ts
  packages/web/app/modules/kyc/selectors.ts
  packages/web/app/test-e2e/eto/InvestUSInvestor.spec.e2e.io.ts
  packages/web/app/test-e2e/neur/NEURUSStateRestrictions.spec.e2e.io.ts
  packages/web/intl/locales/en-en.json
Labels: QA

#3688 #3663 Public soft cap changes - part 2
  packages/web/app/components/App.tsx
  packages/web/app/components/AppRouter.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.module.scss
  packages/web/app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.stories.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/Info.module.scss
  packages/web/app/components/eto/overview/EtoOverviewStatus/Info.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/index.ts
  packages/web/app/components/eto/overview/InvestmentProgress.tsx
  packages/web/app/components/eto/overview/utils.tsx
  packages/web/app/components/eto/shared/EtoView.tsx
  packages/web/app/components/layouts/Container.tsx
  packages/web/app/components/shared/Tabs.tsx
  packages/web/app/modules/eto/utils.ts
  packages/web/app/styles/variables/colors.scss
  packages/web/app/utils/ScrollToTop.tsx
  packages/web/app/utils/ScrollToTop.unsafe.tsx
  packages/web/intl/locales/en-en.json
Labels: QA

#3689 update kyc constants
  packages/web/app/components/settings/kyc-states/KycStatusWidget.tsx
  packages/web/app/lib/api/kyc/KycApi.interfaces.ts
  packages/web/app/modules/kyc/selectors.spec.ts
  packages/web/app/modules/kyc/selectors.ts
  packages/web/app/modules/notifications/selectors.ts
  packages/web/app/test-e2e/utils/userHelpers.ts
  packages/web/package.json
  yarn.lock
Labels: Backend

#3716 Refactor to use create action factory in `investment-flow`, `kyc` and `investment-porfolio`
  packages/web/app/components/shared/forms/fields/FormSingleFileUpload.unsafe.tsx
  packages/web/app/modules/actions.ts
  packages/web/app/modules/investment-flow/actions.ts
  packages/web/app/modules/investment-flow/reducer.ts
  packages/web/app/modules/investment-flow/sagas.ts
  packages/web/app/modules/investor-portfolio/actions.ts
  packages/web/app/modules/investor-portfolio/reducer.ts
  packages/web/app/modules/investor-portfolio/sagas.ts
  packages/web/app/modules/kyc/actions.ts
  packages/web/app/modules/kyc/reducer.ts
  packages/web/app/modules/kyc/sagas.ts
  packages/web/app/modules/notification-modal/actions.ts
  packages/web/app/modules/notification-modal/sagas.ts
  packages/web/app/modules/sagas.ts
  packages/web/health-check-sha.json
Labels: TECH

#3721 #3675 fix bookbuilding widget not loading
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.tsx
  packages/web/app/modules/bookbuilding-flow/utils.ts
  packages/web/app/modules/eto/selectors.ts
  packages/web/app/test-e2e/eto-registration/EtoNomineeAcceptAgreements.spec.e2e.ts
Labels: QA

#3765 Load custom fonts properly
  packages/web/.storybook/setup-styles.ts
  packages/web/app/index.html
  packages/web/app/index.scss
  packages/web/app/index.tsx
Labels: TECH

#3725 #3748 Change form label design to match new NDS
  packages/web/app/components/eto/registration/pages/EtoVotingRights/AdvisoryBoard.tsx
  packages/web/app/components/modals/tx-sender/redeem/BankTransferRedeemInit.tsx
  packages/web/app/components/shared/MultiFileUpload.module.scss
  packages/web/app/components/shared/forms/fields/FormFieldLabel.module.scss
  packages/web/app/components/shared/forms/fields/FormFieldLabel.tsx
  packages/web/app/components/shared/forms/index.tsx
  packages/web/app/components/shared/forms/layouts/FormFieldLayout.tsx
  packages/web/app/components/shared/forms/layouts/FormLabel.module.scss
  packages/web/app/components/shared/forms/layouts/FormLabel.tsx
  packages/web/app/components/shared/forms/layouts/RichTextAreaLayout.tsx
  packages/web/app/lib/api/kyc/KycApi.interfaces.ts
  packages/web/app/styles/mixins/typography.scss
  packages/web/intl/locales/en-en.json
Labels: QA

#3754 #3433 fix etoVotingRights form not saving
  packages/web/app/components/eto/registration/pages/EtoVotingRights/connectEtoVotingRightsForm.ts
Labels: QA

#3687 #3146 Redesign image upload
  packages/web/app/components/eto/registration/pages/CompanyInformation.tsx
  packages/web/app/components/eto/registration/pages/EtoEquityTokenInfo.tsx
  packages/web/app/components/eto/registration/pages/KeyIndividuals.tsx
  packages/web/app/components/eto/shared/EtoAddDocument.tsx
  packages/web/app/components/shared/Document.tsx
  packages/web/app/components/shared/DocumentUploadable.tsx
  packages/web/app/components/shared/Dropzone.stories.tsx
  packages/web/app/components/shared/Dropzone.tsx
  packages/web/app/components/shared/DropzoneActionButtons.tsx
  packages/web/app/components/shared/SingleFileUpload.module.scss
  packages/web/app/components/shared/SingleFileUpload.stories.tsx
  packages/web/app/components/shared/SingleFileUpload.tsx
  packages/web/app/components/shared/buttons/RoundedButton.tsx
  packages/web/app/components/shared/forms/fields/FormSingleFileUpload.tsx
  packages/web/app/components/shared/forms/fields/utils.unsafe.tsx
  packages/web/app/components/translatedMessages/messages.tsx
  packages/web/app/modules/eto-flow/utils.ts
  packages/web/app/test-e2e/eto-registration/EtoCompanyInformationRichTextEditor.spec.e2e.io.ts
  packages/web/app/test-e2e/utils/forms.ts
  packages/web/health-check-sha.json
  packages/web/intl/locales/en-en.json
Labels: QA

#3733 #3599 Improve whitelisting in issuer flow
  packages/web/app/components/eto/overview/EtoOverviewStatus/CampaigningWidget/CampaigningActivatedWidget.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/CampaigningWidget/connectCampaigningActivatedWidget.ts
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/Whitelist/Whitelist.tsx
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingActiveWidget.tsx
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingNotActiveWidget.tsx
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingStats.module.scss
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.tsx
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.module.scss
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.tsx
  packages/web/app/components/modals/tx-sender/eto-flow/SetDateSummary.tsx
  packages/web/app/components/shared/DatePicker.tsx
  packages/web/app/components/shared/Heading.module.scss
  packages/web/app/components/shared/Heading.tsx
  packages/web/app/modules/bookbuilding-flow/utils.ts
  packages/web/intl/locales/en-en.json
Labels: Blocker, QA

#3751 #3322 nominee upload and sign isha
  packages/web/app/components/documents/Documents.stories.tsx
  packages/web/app/components/documents/issuerDocuments/Documents.tsx
  packages/web/app/components/documents/issuerDocuments/DocumentsLayout.tsx
  packages/web/app/components/eto/shared/EtoAddDocument.tsx
  packages/web/app/components/issuer-dashboard/signInvestmentAgreementWidget/SignInvestmentAgreement.tsx
  packages/web/app/components/modals/tx-sender/nominee/sign-isha/SignISHASummary.module.scss
  packages/web/app/components/modals/tx-sender/nominee/sign-isha/SignISHASummary.stories.tsx
  packages/web/app/components/modals/tx-sender/nominee/sign-isha/SignISHASummary.tsx
  packages/web/app/components/nominee-dashboard/AcceptIsha.stories.tsx
  packages/web/app/components/nominee-dashboard/AcceptIsha.tsx
  packages/web/app/components/nominee-dashboard/RedeemShareCapital.tsx
  packages/web/app/components/shared/Document.stories.tsx
  packages/web/app/components/shared/DocumentUploadable.tsx
  packages/web/app/modules/eto-documents/sagas.ts
  packages/web/app/modules/eto-flow/actions.ts
  packages/web/app/modules/eto/sagas.ts
  packages/web/app/modules/nominee-flow/actions.ts
  packages/web/app/modules/nominee-flow/lazy.ts
  packages/web/app/modules/nominee-flow/reducer.ts
  packages/web/app/modules/nominee-flow/sagas.ts
  packages/web/app/modules/nominee-flow/selectors.ts
  packages/web/app/modules/nominee-flow/types.ts
  packages/web/app/modules/nominee-flow/utils.ts
  packages/web/app/modules/tx/transactions/eto-flow/sagas.ts
  packages/web/app/modules/tx/transactions/nominee/sign-agreement/sagas.ts
  packages/web/app/test-e2e/eto-registration/EtoSigningISHAStep.spec.e2e.ts
  packages/web/app/test-e2e/nominee-flow/NomineeFlow.spec.e2e.ts
  packages/web/app/test-e2e/utils/forms.ts
  packages/web/app/test-e2e/utils/index.ts
  packages/web/app/utils/enums/processStates.ts
  packages/web/intl/locales/en-en.json
  packages/web/package.json
  packages/web/typings/hash.d.ts
  yarn.lock
Labels: Blocker

#3766 #3744 Change eto progress bar
  packages/web/app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentStatusWidget.module.scss
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentStatusWidget.stories.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentStatusWidget.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentWidget.module.scss
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentWidget.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/USInvestorMessage.tsx
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/Cover.tsx
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/EtoCardStatusManager.tsx
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/Whitelist/WhitelistProgress.tsx
  packages/web/app/components/eto/overview/InvestmentProgress.tsx
  packages/web/app/components/eto/public-view/EtoInvestmentTermsWidget.tsx
  packages/web/app/components/eto/public-view/JurisdictionDisclaimerModal.tsx
  packages/web/app/components/eto/shared/InvestmentAmount.tsx
  packages/web/app/components/modals/tx-sender/investment-flow/Summary.tsx
  packages/web/app/components/portfolio/PortfolioAssetAction.tsx
  packages/web/app/components/portfolio/PortfolioLayout.module.scss
  packages/web/app/components/portfolio/PortfolioReservedAssets.tsx
  packages/web/app/components/shared/ProgressBarSimple.module.scss
  packages/web/app/components/shared/ProgressBarSimple.stories.tsx
  packages/web/app/components/shared/ProgressBarSimple.tsx
  packages/web/app/lib/api/eto/EtoUtils.spec.ts
  packages/web/app/lib/api/eto/EtoUtils.ts
  packages/web/app/modules/eto/selectors.ts
  packages/web/app/modules/eto/utils.spec.ts
  packages/web/app/modules/eto/utils.ts
  packages/web/health-check-sha.json
  packages/web/intl/locales/en-en.json
Labels: Blocker

#3795 Fix nominee race conditions
  packages/web/app/modules/nominee-flow/sagas.ts
  packages/web/health-check-sha.json
Labels: Bug

#3784 Move PendingTransactions E2E tests to our IO env
  packages/web/app/test-e2e/pending-transactions/SupportForPendingTransactionsDuringTxFlow.spec.e2e.io.ts
  packages/web/app/test-e2e/pending-transactions/SupportForPendingTransactionsDuringTxFlow.spec.e2e.ts
  packages/web/app/test-e2e/pending-transactions/SupportForPendingTransactionsInHeader.spec.e2e.io.ts
  packages/web/app/test-e2e/pending-transactions/SupportForPendingTransactionsInHeader.spec.e2e.ts
  packages/web/app/test-e2e/pending-transactions/generalPendingTxFixture.ts
  packages/web/package.json
  yarn.lock
Labels: E2E test

#3798 Moves PortfolioDownloadDocuments to `io`
  packages/web/app/test-e2e/kyc/KYCFlowIndividualManual.spec.e2e.io.ts
  packages/web/app/test-e2e/kyc/KYCFlowIndividualOutsourced.spec.e2e.io.ts
  packages/web/app/test-e2e/portfolio/PortfolioDownloadDocuments.spec.e2e.io.ts
Labels: E2E test
