Repository Neufund/platform-frontend, pull requests merged in 2019-04, with the labels that each got.

#2720 #2708 - Fix unable to redeem minimal amount
  app/modules/web3/utils.ts
Labels: QA

#2736 #2654 - Update company details page
  app/components/eto/public-view/EtoInvestmentTermsWidget.tsx
  app/lib/api/eto/EtoProductsApi.interfaces.ts
  app/test-e2e/eto-view/EtoViewForInvestor.spec.e2e.ts
  intl/locales/en-en.json
  test/fixtures.ts
Labels: QA

#2719 #2405 - Add Past investments
  app/components/portfolio/Portfolio.tsx
  app/components/portfolio/PortfolioLayout.stories.tsx
  app/components/portfolio/PortfolioLayout.tsx
  app/components/portfolio/PortfolioPastInvestments.stories.tsx
  app/components/portfolio/PortfolioPastInvestments.tsx
  app/modules/investor-portfolio/selectors.ts
  app/modules/investor-portfolio/utils.ts
  app/test-e2e/portfolio/Portfolio.spec.e2e.ts
  intl/locales/en-en.json
Labels: QA

#2745 #2721 Eto terms e2e tests
  app/components/eto/registration/pages/EtoTerms.tsx
  app/components/shared/tooltips/Tooltip.tsx
  app/test-e2e/eto-registration/EtoTerms.spec.e2e.ts
Labels: E2E test

#2755 Turn on react strict mode checks
  app/components/App.tsx
  e2e/run_backend.sh
Labels: TECH

#2763 Add default `react-intl` tag for storybook components
  .storybook/config.js
Labels: TECH

#2771 #2647 Remove logger from form props
  app/components/shared/forms/Form.ts
  app/components/utils/omitProps.ts
Labels: TECH

#2770 #2766 Fix ICBM migration call to action button position
  app/components/settings/icbm-wallet-widget/CheckYourICBMWalletWidget.tsx
Labels: Bug, QA

#2776 #2737 - Add nominee name to ETO details
  app/components/eto/public-view/EtoInvestmentTermsWidget.tsx
  app/lib/api/eto/EtoApi.interfaces.unsafe.tsx
  app/test-e2e/eto-view/EtoViewForInvestor.spec.e2e.ts
Labels: QA

#2747 #2687 Refactor Money Input
  app/components/modals/tx-sender/investment-flow/Investment.stories.tsx
  app/components/modals/tx-sender/investment-flow/Investment.tsx
  app/components/shared/MaskedMoneyInput.stories.tsx
  app/components/shared/MaskedMoneyInput.tsx
  app/components/shared/Money.unsafe.tsx
  app/components/shared/forms/fields/FormInputRaw.spec.tsx
  app/components/shared/forms/fields/FormInputRaw.unsafe.tsx
  app/utils/Money.utils.spec.ts
  app/utils/Money.utils.ts
  intl/locales/en-en.json
Labels: QA

#2783 Remove unused images
  app/assets/img/id_img.svg
  app/assets/img/id_now.svg
  app/assets/img/landing_hero_bg.jpg
  app/assets/img/landing_hero_bg@2x.jpg
  app/assets/img/landing_hero_bg@3x.jpg
  app/assets/img/person.jpg
  app/assets/img/person.png
  app/assets/img/person@2x.jpg
  app/assets/img/person@2x.png
  app/assets/img/person@3x.jpg
  app/assets/img/person@3x.png
  app/components/settings/personal-account-details/PersonalAccountDetails.tsx
  app/test-e2e/eto-registration/EtoTerms.spec.e2e.ts
  e2e/run_backend.sh
Labels: TECH

#2775 #2543 - Add e2e tests for redeem flow
  app/components/modals/tx-sender/redeem/BankTransferRedeemDetails.tsx
  app/components/modals/tx-sender/redeem/BankTransferRedeemInit.unsafe.tsx
  app/components/modals/tx-sender/redeem/BankTransferRedeemSuccess.tsx
  app/components/modals/tx-sender/redeem/BankTransferRedeemSummary.tsx
  app/test-e2e/bank-transfer/RedeemNEUR.spec.e2e.ts
  app/test-e2e/fixtures.ts
  app/test-e2e/utils/index.ts
Labels: TECH

#2782 Fix css styles order differences
  app/components/kyc/business/BeneficialOwners.module.scss
  app/components/kyc/business/BeneficialOwners.tsx
  app/index.tsx
  app/styles/overrides.scss
  webpack/webpack.config.dev.js
  webpack/webpack.config.prod.js
Labels: Bug, QA

#2780 #2760 - Adds ledger not supported message
  app/components/translatedMessages/messages.tsx
  app/components/wallet-selector/ledger/WalletLedgerInitComponent.spec.tsx
  app/components/wallet-selector/ledger/WalletLedgerInitComponent.tsx
  app/components/wallet/wallet-balance/UnlockedETHWallet.tsx
  app/config/externalRoutes.ts
  app/lib/web3/ledger-wallet/ledgerUtils.ts
  app/modules/wallet-selector/ledger-wizard/errors.ts
  docs/component-development-guidelines.md
  intl/locales/en-en.json
  package.json
  yarn.lock
Labels: QA

#2798 #2794 - Update Ngrave ETO card
  app/assets/img/eto_offers/ngrave.jpg
  app/assets/img/eto_offers/ngrave@2x.jpg
  app/assets/img/eto_offers/ngravehover@1x.jpg
  app/assets/img/eto_offers/ngravehover@2x.jpg
Labels: QA

#2774 #2663 - Update TOS modal
  app/assets/img/tos.jpg
  app/components/modals/accept-tos-modal/AcceptTosModal.module.scss
  app/components/modals/accept-tos-modal/AcceptTosModal.tsx
  app/components/shared/buttons/Button.module.scss
  app/modules/auth/selectors.ts
  intl/locales/en-en.json
Labels: QA

#2740 #2570 - Add Bank transfer fee tooltip
  app/components/modals/tx-sender/redeem/BankTransferRedeemInit.unsafe.tsx
  app/components/shared/tooltips/Tooltip.module.scss
  intl/locales/en-en.json
Labels: QA

#2803 Update router related dependencies
  package.json
  yarn.lock
Labels: TECH

#2731 #2221 - Show not enabled ICBM wallets on Investment flow
  app/components/modals/tx-sender/investment-flow/Investment.stories.tsx
  app/components/modals/tx-sender/investment-flow/Investment.tsx
  app/components/modals/tx-sender/investment-flow/InvestmentTypeSelector.module.scss
  app/components/modals/tx-sender/investment-flow/InvestmentTypeSelector.stories.tsx
  app/components/modals/tx-sender/investment-flow/InvestmentTypeSelector.tsx
  app/components/modals/tx-sender/investment-flow/utils.tsx
  app/components/modals/tx-sender/upgrade-flow/Summary.unsafe.tsx
  app/test-e2e/eto/InvestStartUpgradeFlow.spec.e2e.ts
  app/test-e2e/wallets/WalletUpgrade.spec.e2e.ts
  app/utils/storybookHelpers.unsafe.tsx
  intl/locales/en-en.json
Labels: QA

#2818 #2779 - Updates Banned Countries list
  app/lib/api/util/schemaHelpers.unsafe.tsx
Labels: QA
