Repository Neufund/platform-frontend, pull requests merged in 2019-09, with the labels that each got.

#3391 Improve codechecks bundle watcher and minor fixes
  package.json
  packages/web/.storybook/config.js
  packages/web/app/components/eto/public-view/EtoAccordionElements.tsx
  packages/web/app/components/eto/public-view/LegalInformationWidget.tsx
  packages/web/app/components/shared/charts/ChartDoughnutLazy.tsx
  packages/web/app/utils/storeDecorator.unsafe.tsx
  packages/web/codechecks.json
  packages/web/health-check-sha.json
  packages/web/package.json
  packages/web/webpack/webpack.config.common.js
  patches/bitcore-mnemonic+8.3.3.patch
Labels: TECH

#3381 #3250 token holder rights form
  packages/web/app/components/eto/registration/Router.tsx
  packages/web/app/components/eto/registration/Shared.module.scss
  packages/web/app/components/eto/registration/pages/AllForms.stories.tsx
  packages/web/app/components/eto/registration/pages/EtoVotingRights.tsx
  packages/web/app/components/eto/registration/pages/EtoVotingRights/AdvisoryBoard.tsx
  packages/web/app/components/eto/registration/pages/EtoVotingRights/EtoVotingRights.tsx
  packages/web/app/components/eto/registration/pages/EtoVotingRights/connectEtoVotingRightsForm.ts
  packages/web/app/components/eto/registration/pages/Nominee/Nominee.tsx
  packages/web/app/components/eto/utils.spec.ts
  packages/web/app/components/eto/utils.ts
  packages/web/app/components/shared/MaskedNumberInput.tsx
  packages/web/app/components/shared/forms/Form.ts
  packages/web/app/components/shared/forms/fields/FormFieldBoolean.tsx
  packages/web/app/components/shared/forms/fields/FormMaskedNumberInput.tsx
  packages/web/app/components/shared/forms/fields/FormStaticRadioButton.module.scss
  packages/web/app/components/shared/forms/fields/FormStaticRadioButton.stories.tsx
  packages/web/app/components/shared/forms/fields/FormStaticRadioButton.tsx
  packages/web/app/components/shared/forms/fields/FormTextArea.tsx
  packages/web/app/components/shared/forms/layouts/InputLayout.tsx
  packages/web/app/config/constants.ts
  packages/web/app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  packages/web/app/modules/nominee-flow/sagas.ts
  packages/web/app/modules/tx/transactions/nominee/sign-agreement/saga.ts
  packages/web/app/test-e2e/eto-registration/2.EtoRequiredReqistrationAndSubmit.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-registration/EtoLinkNomineeStep.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-registration/fixtures.ts
  packages/web/app/utils/errors.ts
  packages/web/intl/locales/en-en.json
  packages/web/test/fixtures.ts
Labels: QA

#3400 Rename shareholder form
  packages/web/app/components/issuer-dashboard/EtoDashboard.tsx
  packages/web/app/components/issuer-dashboard/dashboardStep/LinkNomineeStep.tsx
  packages/web/health-check-sha.json
  packages/web/intl/locales/en-en.json
Labels: QA

#3407 Fix key individuals form empty submit
  packages/web/app/components/eto/registration/pages/KeyIndividuals.tsx
  packages/web/app/test-e2e/1.long-e2e-tests/1.FullEtoRegistrationAndSubmit.spec.e2e.io.ts
  packages/web/app/test-e2e/1.long-e2e-tests/2.ChangeEmail.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-registration/fixtures.ts
  packages/web/app/test-e2e/register/LightWalletETORegister.spec.e2e.io.ts
  packages/web/app/test-e2e/utils/generateRandomSeedAndAddress.spec.node.ts
  packages/web/app/test-e2e/utils/generateSeedAndAddress.spec.node.ts
  packages/web/app/test-e2e/wallets/WalletRecover.spec.e2e.io.ts
Labels: QA

#3409 #3230 Fix only public route to wait for auth state
  packages/web/app/components/App.tsx
  packages/web/app/components/shared/routing/OnlyPublicRoute.tsx
  packages/web/app/modules/auth/actions.ts
  packages/web/app/modules/auth/reducer.ts
  packages/web/app/modules/auth/sagas.ts
  packages/web/app/modules/web3/actions.ts
  packages/web/app/test-e2e/eto-registration/EtoLinkNomineeStep.spec.e2e.io.ts
  packages/web/health-check-sha.json
Labels: QA

#3399 #3384 #3394 ISHA upload and waiting for contracts issuer steps
  packages/web/app/components/issuer-dashboard/EtoDashboard.stories.tsx
  packages/web/app/components/issuer-dashboard/EtoDashboard.tsx
  packages/web/app/components/issuer-dashboard/UploadISHA.tsx
  packages/web/app/components/issuer-dashboard/UploadInvestmentMemorandum.tsx
  packages/web/app/components/issuer-dashboard/UploadProspectusWidget.tsx
  packages/web/app/components/issuer-dashboard/UploadTermSheetWidget.tsx
  packages/web/app/components/issuer-dashboard/dashboardStep/DashboardStep.tsx
  packages/web/app/components/issuer-dashboard/signInvestmentAgreementWidget/UploadInvestmentAgreementWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/signInvestmentAgreementWidget/UploadInvestmentAgreementWidget.tsx
  packages/web/app/components/issuer-dashboard/utils.spec.ts
  packages/web/app/components/issuer-dashboard/utils.ts
  packages/web/app/components/shared/dashboard-link-widget/DashboardLinkWidget.module.scss
  packages/web/app/components/shared/dashboard-link-widget/DashboardLinkWidget.stories.tsx
  packages/web/app/components/shared/dashboard-link-widget/DashboardLinkWidget.tsx
  packages/web/app/modules/eto-flow/selectors.ts
  packages/web/app/test-e2e/eto-registration/2.EtoRequiredReqistrationAndSubmit.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-registration/EtoRegistrationUtils.ts
  packages/web/app/test-e2e/eto-registration/EtoUploadOfferingAndISHADocumentsSteps.spec.e2e.ts
  packages/web/app/test-e2e/utils/forms.ts
  packages/web/cypress/fixtures/example2.pdf
  packages/web/health-check-sha.json
  packages/web/intl/locales/en-en.json
Labels: QA

#3419 #3411 eto header fix
  packages/web/app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.module.scss
  packages/web/app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/TokenSymbolWidget.module.scss
  packages/web/app/components/eto/overview/EtoOverviewStatus/TokenSymbolWidget.tsx
  packages/web/app/components/eto/public-view/CompanyDescription.tsx
  packages/web/app/components/eto/public-view/Cover.module.scss
  packages/web/app/components/eto/public-view/Cover.tsx
  packages/web/app/components/eto/public-view/CoverBanner.module.scss
  packages/web/app/components/eto/shared/EtoView.tsx
  packages/web/app/components/shared/ResponsiveImage.tsx
  packages/web/app/styles/variables/spacings.scss
  packages/web/intl/locales/en-en.json
Labels: QA

#3425 Issuer flow text changes
  packages/web/app/components/issuer-dashboard/submitProposalWidget/SubmitProposalWidget.tsx
  packages/web/intl/locales/en-en.json
Labels: QA

#3392 [All devs approval required] Cache redux selector to prevent rerendering
  packages/web/app/components/App.tsx
  packages/web/app/components/modals/download-token-agreements-modal/DownloadTokenAgreementModal.tsx
  packages/web/app/components/modals/tx-sender/user-claim/Summary.stories.tsx
  packages/web/app/components/modals/tx-sender/user-claim/Summary.tsx
  packages/web/app/components/shared/forms/fields/FormSingleFileUpload.unsafe.tsx
  packages/web/app/components/shared/forms/layouts/RichTextAreaLayout.tsx
  packages/web/app/components/shared/notification-widget/NotificationWidget.tsx
  packages/web/app/modules/eto-flow/selectors.ts
  packages/web/app/modules/eto/selectors.ts
  packages/web/app/modules/immutable-file/selectors.ts
  packages/web/app/modules/notifications/reducer.ts
  packages/web/app/modules/notifications/selectors.ts
  packages/web/package.json
  yarn.lock
Labels: TECH

#3417 [Nominee] Add ability to change active ETO
  packages/web/app/components/documents/nomineeDocuments/NomineeDocuments.tsx
  packages/web/app/components/eto/EtoNomineeView.tsx
  packages/web/app/components/eto/registration/pages/Nominee/ChooseNominee.tsx
  packages/web/app/components/eto/registration/pages/Nominee/utils.ts
  packages/web/app/components/eto/shared/hocs/withNomineeRequests.ts
  packages/web/app/components/layouts/menus/utils.ts
  packages/web/app/components/modals/tx-sender/nominee/sign-agreement/SignAgreementSummary.tsx
  packages/web/app/components/nominee-dashboard/AcceptAgreement.tsx
  packages/web/app/components/nominee-dashboard/NomineeDashboard.tsx
  packages/web/app/components/nominee-dashboard/NomineeDashboardTasks.tsx
  packages/web/app/components/nominee-dashboard/NomineeTasksData.tsx
  packages/web/app/components/nominee-dashboard/linkToIssuer/LinkToIssuer.tsx
  packages/web/app/components/nominee-dashboard/linkToIssuer/NomineeRequestPending.tsx
  packages/web/app/components/nominee-dashboard/linkToIssuer/utils.ts
  packages/web/app/components/nominee-dashboard/nomineeDashboardContainer/LinkedNomineeDashboardContainer.tsx
  packages/web/app/components/nominee-dashboard/nomineeDashboardContainer/NomineeDashboardContainer.tsx
  packages/web/app/components/translatedMessages/messages.tsx
  packages/web/app/components/wallet-selector/light/Login/LoginLightWallet.tsx
  packages/web/app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  packages/web/app/lib/api/eto/EtoApi.ts
  packages/web/app/lib/api/eto/EtoNomineeApi.ts
  packages/web/app/modules/auth/email/sagas.ts
  packages/web/app/modules/eto-documents/selectors.ts
  packages/web/app/modules/eto-flow/actions.ts
  packages/web/app/modules/eto-flow/types.ts
  packages/web/app/modules/eto-flow/utils.spec.ts
  packages/web/app/modules/eto-nominee/actions.ts
  packages/web/app/modules/eto-nominee/reducer.ts
  packages/web/app/modules/eto-nominee/sagas.ts
  packages/web/app/modules/eto/actions.ts
  packages/web/app/modules/eto/sagas.ts
  packages/web/app/modules/eto/selectors.ts
  packages/web/app/modules/investor-portfolio/sagas.ts
  packages/web/app/modules/kyc/sagas.ts
  packages/web/app/modules/nominee-flow/actions.ts
  packages/web/app/modules/nominee-flow/reducer.ts
  packages/web/app/modules/nominee-flow/sagas.ts
  packages/web/app/modules/nominee-flow/selectors.ts
  packages/web/app/modules/nominee-flow/types.ts
  packages/web/app/modules/nominee-flow/utils.ts
  packages/web/app/modules/tx/transactions/nominee/sign-agreement/saga.ts
  packages/web/app/modules/tx/transactions/nominee/sign-agreement/types.ts
  packages/web/app/modules/wallet-selector/light-wizard/metadata/sagas.ts
  packages/web/app/modules/web3/selectors.spec.ts
  packages/web/app/modules/web3/selectors.ts
  packages/web/app/test-e2e/nominee-flow/NomineeChangeActiveEto.spec.e2e.io.ts
  packages/web/app/test-e2e/nominee-flow/NomineeFlow.spec.e2e.io.ts
  packages/web/app/test-e2e/utils/navigation.ts
  packages/web/app/test-e2e/utils/userHelpers.ts
  packages/web/intl/locales/en-en.json
Labels: QA

#3431 #2425 Add custom X-NF-Authorization header to AuthHttpClient
  packages/web/app/lib/api/client/AuthHttpClient.ts
Labels: QA

#3406 #3329 pending payout fix
  packages/web/app/components/dashboard/incoming-payout/IncomingPayoutWidget.stories.tsx
  packages/web/app/components/dashboard/incoming-payout/IncomingPayoutWidget.tsx
  packages/web/app/components/dashboard/my-portfolio/MyNeuWidget.stories.tsx
  packages/web/app/components/dashboard/my-portfolio/MyNeuWidget.tsx
  packages/web/app/components/dashboard/my-portfolio/MyPortfolioWidget.module.scss
  packages/web/app/components/dashboard/my-portfolio/MyPortfolioWidget.stories.tsx
  packages/web/app/components/dashboard/my-portfolio/MyPortfolioWidget.tsx
  packages/web/app/components/dashboard/my-portfolio/my-neu-widget/MyNeuWidget.module.scss
  packages/web/app/components/dashboard/my-portfolio/my-neu-widget/MyNeuWidget.stories.tsx
  packages/web/app/components/dashboard/my-portfolio/my-neu-widget/MyNeuWidget.tsx
  packages/web/app/components/dashboard/my-portfolio/my-neu-widget/MyNeuWidgetError.tsx
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/IncomingPayoutAvailable.tsx
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/IncomingPayoutPending.tsx
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/IncomingPayoutWaiting.tsx
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/PayoutWidget.module.scss
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/PayoutWidget.spec.tsx
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/PayoutWidget.stories.tsx
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/PayoutWidget.ts
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/PayoutWidgetError.tsx
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/WelcomeToNeufund.tsx
  packages/web/app/components/shared/Counter.module.scss
  packages/web/app/components/shared/Counter.stories.tsx
  packages/web/app/components/shared/Counter.unsafe.tsx
  packages/web/app/components/shared/WarningAlert.tsx
  packages/web/app/components/shared/buttons/Button.tsx
  packages/web/app/components/shared/routing/OnlyPublicRoute.tsx
  packages/web/app/components/wallet-selector/WalletSelector.integration.spec.tsx
  packages/web/app/components/wallet/views/start/Start.tsx
  packages/web/app/config/constants.ts
  packages/web/app/config/externalRoutes.ts
  packages/web/app/modules/contracts/utils.ts
  packages/web/app/modules/investor-portfolio/__tests__/selectors.spec.ts
  packages/web/app/modules/investor-portfolio/actions.ts
  packages/web/app/modules/investor-portfolio/reducer.ts
  packages/web/app/modules/investor-portfolio/sagas.ts
  packages/web/app/modules/investor-portfolio/selectors.ts
  packages/web/app/modules/investor-portfolio/types.ts
  packages/web/app/modules/investor-portfolio/utils.spec.ts
  packages/web/app/modules/investor-portfolio/utils.ts
  packages/web/app/modules/wallet/selectors.ts
  packages/web/app/utils/errors.ts
Labels: QA

#3434 #3411 eto header fix
  packages/web/app/components/eto/public-view/Cover.module.scss
Labels: QA

#3435 [Production hotfix] ##3411 eto header
  packages/web/app/components/eto/public-view/Cover.module.scss
Labels: QA

#3418 #3256 eto terms submit more data than should
  packages/web/app/components/eto/overview/EtoOverviewStatus/CampaigningWidget/CampaigningActivatedInvestorApprovedWidgetLayout.tsx
  packages/web/app/components/eto/registration/EtoFormBase.tsx
  packages/web/app/components/eto/registration/pages/AllForms.stories.tsx
  packages/web/app/components/eto/registration/pages/CompanyInformation.tsx
  packages/web/app/components/eto/registration/pages/EtoEquityTokenInfo.tsx
  packages/web/app/components/eto/registration/pages/EtoMedia.tsx
  packages/web/app/components/eto/registration/pages/EtoPitch.tsx
  packages/web/app/components/eto/registration/pages/EtoTerms.stories.tsx
  packages/web/app/components/eto/registration/pages/EtoTerms.tsx
  packages/web/app/components/eto/registration/pages/EtoVotingRights/EtoVotingRights.tsx
  packages/web/app/components/eto/registration/pages/EtoVotingRights/connectEtoVotingRightsForm.ts
  packages/web/app/components/eto/registration/pages/InvestmentTerms.stories.tsx
  packages/web/app/components/eto/registration/pages/InvestmentTerms.tsx
  packages/web/app/components/eto/registration/pages/KeyIndividuals.tsx
  packages/web/app/components/eto/registration/pages/LegalInformation.tsx
  packages/web/app/components/eto/registration/pages/RiskAssessment.tsx
  packages/web/app/components/kyc/business/BeneficialOwner.unsafe.tsx
  packages/web/app/components/kyc/business/BusinessData.unsafe.tsx
  packages/web/app/components/kyc/business/LegalRepresentative.unsafe.tsx
  packages/web/app/components/kyc/personal/Start.unsafe.tsx
  packages/web/app/components/modals/bank-transfer-flow/shared/BankTransferAgreement.tsx
  packages/web/app/components/modals/tx-sender/nominee/sign-agreement/SignAgreementSummary.tsx
  packages/web/app/components/modals/tx-sender/redeem/BankTransferRedeemInit.tsx
  packages/web/app/components/modals/tx-sender/user-claim/SummaryForm.unsafe.tsx
  packages/web/app/components/modals/tx-sender/withdraw-flow/withdraw/Withdraw.tsx
  packages/web/app/components/modals/wallet-access/AccessLightWalletPrompt.tsx
  packages/web/app/components/settings/icbm-wallet-widget/CheckYourICBMWalletWidget.tsx
  packages/web/app/components/settings/verify-email/AccountSetupVerifyEmailComponent.tsx
  packages/web/app/components/settings/verify-email/VerifyEmailWidget.tsx
  packages/web/app/components/shared/SocialProfilesEditor.tsx
  packages/web/app/components/shared/forms/Form.spec.tsx
  packages/web/app/components/shared/forms/Form.tsx
  packages/web/app/components/shared/forms/FormDeprecated.ts
  packages/web/app/components/shared/forms/fields/FormCategoryDistribution.unsafe.tsx
  packages/web/app/components/shared/forms/fields/FormField.stories.tsx
  packages/web/app/components/shared/forms/fields/FormFieldColorful.stories.tsx
  packages/web/app/components/shared/forms/fields/FormFieldDate.stories.tsx
  packages/web/app/components/shared/forms/fields/FormRange.tsx
  packages/web/app/components/shared/forms/fields/testingUtils.unsafe.tsx
  packages/web/app/components/shared/forms/fields/utils.unsafe.tsx
  packages/web/app/components/shared/forms/index.tsx
  packages/web/app/components/shared/forms/layouts/RichTextAreaLayout.tsx
  packages/web/app/components/shared/hooks/usePrevious.spec.tsx
  packages/web/app/components/shared/hooks/usePrevious.ts
  packages/web/app/components/wallet-selector/light/Login/LoginWithEmailLightWallet.unsafe.tsx
  packages/web/app/components/wallet-selector/light/Register/RegisterLightWallet.unsafe.tsx
  packages/web/app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  packages/web/app/lib/api/eto/EtoApi.ts
  packages/web/app/lib/api/kyc/KycApi.interfaces.ts
  packages/web/app/lib/api/util/customSchemas.unsafe.ts
  packages/web/app/modules/eto-flow/sagas.ts
  packages/web/app/test-e2e/eto-registration/EtoCompanyInformationFieldValidation.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-registration/EtoCompanyInformationRichTextEditor.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-registration/EtoCompanyInformationSubmission.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-registration/EtoRegistrationUtils.ts
  packages/web/app/test-e2e/eto-registration/EtoRequiredReqistrationAndSubmit.spec.e2e.io.ts
  packages/web/app/types.d.ts
  packages/web/app/utils/yupUtils.spec.ts
  packages/web/app/utils/yupUtils.ts
Labels: QA

#3446 Adds etoLoading, etoSaving selectors
  packages/web/app/components/eto/registration/Start.tsx
  packages/web/app/components/eto/registration/pages/CompanyInformation.tsx
  packages/web/app/components/eto/registration/pages/EtoEquityTokenInfo.tsx
  packages/web/app/components/eto/registration/pages/EtoMedia.tsx
  packages/web/app/components/eto/registration/pages/EtoPitch.tsx
  packages/web/app/components/eto/registration/pages/EtoTerms.tsx
  packages/web/app/components/eto/registration/pages/EtoVotingRights/connectEtoVotingRightsForm.ts
  packages/web/app/components/eto/registration/pages/InvestmentTerms.tsx
  packages/web/app/components/eto/registration/pages/KeyIndividuals.tsx
  packages/web/app/components/eto/registration/pages/RiskAssessment.tsx
  packages/web/app/modules/eto-flow/selectors.ts
Labels: TECH

#3466 Reduces Broadcast Channel Protocols
  packages/web/app/lib/dependencies/broadcast-channel/broadcastChannel.ts
  packages/web/app/test-e2e/general-app/autoLoginLogoutActions.spec.e2e.io.ts
  packages/web/package.json
  yarn.lock
Labels: QA

#3455 fixes token formatting portfolio
  packages/web/app/components/documents/utils.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/EtoStats.tsx
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/EtoStatusManager.tsx
  packages/web/app/components/eto/registration/pages/InvestmentTerms.spec.tsx
  packages/web/app/components/eto/registration/pages/InvestmentTerms.tsx
  packages/web/app/components/eto/shared/ETOState.tsx
  packages/web/app/components/issuer-dashboard/EtoDashboard.tsx
  packages/web/app/components/issuer-dashboard/dashboardStep/DashboardStep.tsx
  packages/web/app/components/issuer-dashboard/utils.ts
  packages/web/app/components/portfolio/PortfolioMyAssets.tsx
  packages/web/app/components/shared/formatters/utils.ts
  packages/web/app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  packages/web/app/lib/api/eto/EtoUtils.spec.ts
  packages/web/app/lib/api/eto/EtoUtils.ts
  packages/web/app/modules/eto/sagas.ts
  packages/web/app/modules/eto/utils.ts
  packages/web/app/styles/variables/colors.scss
  packages/web/intl/locales/en-en.json
  packages/web/test/fixtures.ts
Labels: QA

#3473 Fixes showing false ETO dates
  packages/web/app/components/eto/overview/EtoTimeline/EtoTimeline.stories.tsx
  packages/web/app/components/eto/overview/EtoTimeline/EtoTimeline.tsx
  packages/web/health-check-sha.json
Labels: QA

#3471 Whitelisting tooltip copy update
  packages/web/intl/locales/en-en.json
Labels: QA

#3478 fixes pre-sale visibility
  packages/web/app/modules/investor-portfolio/selectors.ts
Labels: Bug, QA

#3472 Add Fill your eto information step for issuer
  packages/web/app/components/issuer-dashboard/EtoDashboard.tsx
  packages/web/app/components/issuer-dashboard/dashboardStep/DashboardStep.tsx
  packages/web/app/components/issuer-dashboard/utils.spec.ts
  packages/web/app/components/issuer-dashboard/utils.ts
  packages/web/app/test-e2e/eto-registration/EtoLinkNomineeStep.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-registration/EtoRegistrationUtils.ts
  packages/web/health-check-sha.json
  packages/web/intl/locales/en-en.json
Labels: QA

#3444 #3395 Issuer steps 14, 15, 16.
  packages/web/app/components/documents/utils.tsx
  packages/web/app/components/issuer-dashboard/EtoDashboard.stories.tsx
  packages/web/app/components/issuer-dashboard/EtoDashboard.tsx
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.tsx
  packages/web/app/components/issuer-dashboard/dashboardStep/DashboardStep.tsx
  packages/web/app/components/issuer-dashboard/signInvestmentAgreementWidget/UploadInvestmentAgreementWidget.tsx
  packages/web/app/components/issuer-dashboard/utils.spec.ts
  packages/web/app/components/issuer-dashboard/utils.ts
  packages/web/app/components/modals/tx-sender/eto-flow/SetDateSummary.unsafe.tsx
  packages/web/app/components/nominee-dashboard/AcceptAgreement.tsx
  packages/web/app/components/nominee-dashboard/NomineeDashboard.tsx
  packages/web/app/components/nominee-dashboard/NomineeDashboardTasks.tsx
  packages/web/app/modules/bank-transfer-flow/sagas.ts
  packages/web/app/modules/eto-flow/actions.ts
  packages/web/app/modules/eto-flow/sagas.ts
  packages/web/app/modules/eto-flow/selectors.ts
  packages/web/app/modules/eto/actions.ts
  packages/web/app/modules/eto/reducer.ts
  packages/web/app/modules/eto/sagas.ts
  packages/web/app/modules/eto/selectors.ts
  packages/web/app/modules/eto/types.ts
  packages/web/app/modules/nominee-flow/reducer.ts
  packages/web/app/modules/nominee-flow/sagas.ts
  packages/web/app/modules/nominee-flow/selectors.ts
  packages/web/app/modules/nominee-flow/types.ts
  packages/web/app/modules/nominee-flow/utils.ts
  packages/web/app/modules/tx/transactions/nominee/sign-agreement/saga.ts
  packages/web/app/test-e2e/eto-registration/EtoNomineeAcceptAgreements.spec.e2e.ts
  packages/web/app/test-e2e/eto-registration/EtoRegistrationUtils.ts
  packages/web/app/test-e2e/nominee-flow/NomineeAgreementsAcceptanceFlow.spec.e2e.ts
  packages/web/app/test-e2e/nominee-flow/NomineeFlowUtils.ts
  packages/web/app/types.d.ts
  packages/web/cypress/support/commands.js
  packages/web/intl/locales/en-en.json
  packages/web/test/fixtures.ts
Labels: QA

#3490 #3479 Show current funding round
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/PayoutWidget.spec.tsx
  packages/web/app/components/eto/constants.tsx
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/EtoOverviewThumbnail.tsx
  packages/web/app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  packages/web/app/lib/api/eto/EtoApiUtils.ts
  packages/web/app/test-e2e/eto-view/EtoWidget.spec.e2e.io.ts
  packages/web/test/fixtures.ts
Labels: QA

#3491 Turn on no shadowed variable tslint rule
  packages/shared/tslint.json
  packages/web/app/components/settings/backup-seed/BackupSeedVerify.unsafe.tsx
  packages/web/app/components/shared/AccountBalance.tsx
  packages/web/app/components/shared/charts/ChartDoughnut.unsafe.tsx
  packages/web/app/components/shared/forms/layouts/RichTextAreaLayout.tsx
  packages/web/app/components/wallet-selector/ledger/WalletLedger.tsx
  packages/web/app/di/symbols.ts
  packages/web/app/di/symbolsUtils.ts
  packages/web/app/lib/api/client/HTTPClient.spec.ts
  packages/web/app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  packages/web/app/lib/api/eto/EtoFileApi.interfaces.ts
  packages/web/app/lib/dependencies/logger/utils.ts
  packages/web/app/lib/yup-ts.spec.ts
  packages/web/app/modules/eto/selectors.ts
  packages/web/app/modules/kyc/reducer.ts
  packages/web/app/test-e2e/register/LightWalletETOLogin.spec.e2e.io.ts
  packages/web/app/test-e2e/wallets/WalletMigrate.spec.e2e.ts
  packages/web/app/utils/yupUtils.ts
Labels: TECH

#3477 Sync dashboard widgets to use the same base component
  packages/web/app/components/eto/EtoContentWidget.module.scss
  packages/web/app/components/issuer-dashboard/PublishETOWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/PublishETOWidget.tsx
  packages/web/app/components/issuer-dashboard/UploadISHA.tsx
  packages/web/app/components/issuer-dashboard/UploadInvestmentMemorandum.tsx
  packages/web/app/components/issuer-dashboard/UploadProspectusWidget.tsx
  packages/web/app/components/issuer-dashboard/UploadTermSheetWidget.tsx
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.module.scss
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.tsx
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.module.scss
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.tsx
  packages/web/app/components/issuer-dashboard/signInvestmentAgreementWidget/SignInvestmentAgreement.tsx
  packages/web/app/components/issuer-dashboard/signInvestmentAgreementWidget/UploadInvestmentAgreementWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/signInvestmentAgreementWidget/UploadInvestmentAgreementWidget.tsx
  packages/web/app/components/issuer-dashboard/submitProposalWidget/SubmitProposalWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/submitProposalWidget/SubmitProposalWidget.tsx
  packages/web/app/components/shared/dashboard-link-widget/DashboardLinkWidget.module.scss
  packages/web/app/components/shared/dashboard-link-widget/DashboardLinkWidget.stories.tsx
  packages/web/app/components/shared/dashboard-link-widget/DashboardLinkWidget.tsx
  packages/web/app/components/shared/dashboard-widget/DashboardWidget.module.scss
  packages/web/app/components/shared/dashboard-widget/DashboardWidget.stories.tsx
  packages/web/app/components/shared/dashboard-widget/DashboardWidget.tsx
  packages/web/intl/locales/en-en.json
Labels: QA

#3448 #3447 hasDividendRights field name fix
  packages/web/app/components/eto/registration/pages/EtoVotingRights/EtoVotingRights.tsx
  packages/web/app/components/shared/forms/Form.tsx
  packages/web/app/components/shared/forms/FormDeprecated.ts
Labels: Reviewed

#3496 #3308 #3307 Fix My Assets
  packages/web/app/components/modals/tx-sender/user-claim/Success.tsx
  packages/web/app/components/modals/tx-sender/user-claim/SummaryForm.unsafe.tsx
  packages/web/app/modules/investor-portfolio/selectors.ts
  packages/web/app/modules/tx/transactions/sagas.ts
  packages/web/app/test-e2e/portfolio/TokenClaim.spec.e2e.ts
Labels: QA

#3516 #3357 ETH Balance widget copy changes
  packages/web/app/components/modals/DepositEthModal.module.scss
  packages/web/app/components/wallet/wallet-balance/UnlockedETHWallet.tsx
  packages/web/intl/locales/en-en.json
Labels: QA

#3503 Move to LINK NOMINEE after marketing data were submitted
  packages/web/app/components/issuer-dashboard/EtoDashboard.tsx
  packages/web/app/components/issuer-dashboard/PublishETOWidget.tsx
  packages/web/app/components/issuer-dashboard/utils.spec.ts
  packages/web/app/components/issuer-dashboard/utils.ts
  packages/web/app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  packages/web/app/modules/eto-flow/utils.ts
  packages/web/app/test-e2e/eto-registration/EtoLinkNomineeStep.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-registration/EtoRegistrationUtils.ts
  packages/web/intl/locales/en-en.json
Labels: QA

#3523 #3424 #3436 Minor fixes to transactions history
  packages/web/app/components/shared/table/NewTable.module.scss
  packages/web/app/components/wallet/transactions-history/TransactionsHistory.tsx
  packages/web/intl/locales/en-en.json
Labels: QA

#3550 adds empty string checks for our translation files
  packages/web/scripts/mergeMessagesWithLocales.js
Labels: TECH

#3522 #3438 add sign isha step
  packages/web/app/components/documents/issuerDocuments/Documents.tsx
  packages/web/app/components/issuer-dashboard/dashboardStep/DashboardStep.tsx
  packages/web/app/components/issuer-dashboard/signInvestmentAgreementWidget/SignInvestmentAgreement.tsx
  packages/web/app/components/issuer-dashboard/signInvestmentAgreementWidget/UploadInvestmentAgreementWidget.tsx
  packages/web/app/components/issuer-dashboard/utils.ts
  packages/web/app/components/modals/tx-sender/TxSender.tsx
  packages/web/app/components/modals/tx-sender/eto-flow/SetDateSummary.stories.tsx
  packages/web/app/components/modals/tx-sender/eto-flow/SetDateSummary.tsx
  packages/web/app/components/modals/tx-sender/eto-flow/SignInvestmentAgreementSummary.module.scss
  packages/web/app/components/modals/tx-sender/eto-flow/SignInvestmentAgreementSummary.tsx
  packages/web/app/config/externalRoutes.ts
  packages/web/app/modules/eto-documents/sagas.ts
  packages/web/app/modules/eto-flow/actions.ts
  packages/web/app/modules/eto-flow/selectors.ts
  packages/web/app/modules/eto/errors.ts
  packages/web/app/modules/tx/transactions/eto-flow/saga.ts
  packages/web/app/modules/tx/transactions/sagas.ts
  packages/web/app/test-e2e/1.long-e2e-tests/2.ChangeEmail.spec.e2e.io.ts
  packages/web/app/test-e2e/bank-transfer/RedeemNEUR.spec.e2e.ts
  packages/web/app/test-e2e/eto-registration/EtoRegistrationUtils.ts
  packages/web/app/test-e2e/eto-registration/EtoSigningISHAStep.spec.e2e.ts
  packages/web/app/test-e2e/eto/Refund.spec.e2e.ts
  packages/web/app/test-e2e/general-app/JWTEscalationAndRefreshing.spec.e2e.io.ts
  packages/web/app/test-e2e/nominee-flow/NomineeFlowUtils.ts
  packages/web/app/test-e2e/portfolio/TokenClaim.spec.e2e.ts
  packages/web/app/test-e2e/utils/forms.ts
  packages/web/app/test-e2e/utils/index.ts
  packages/web/intl/locales/en-en.json
Labels: QA
