Repository Neufund/platform-frontend, pull requests merged in 2019-10, with the labels that each got.

#3555 #3526 fetch ETO data after investment succeeded
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentWidget.tsx
  packages/web/app/modules/investment-flow/sagas.ts
  packages/web/app/modules/tx/sender/sagas.ts
  packages/web/app/modules/tx/transactions/actions.ts
  packages/web/app/modules/tx/transactions/investment/sagas.ts
  packages/web/app/modules/tx/transactions/sagas.ts
  packages/web/app/test-e2e/eto-view/EtoViewForInvestor.spec.e2e.io.ts
  packages/web/app/test-e2e/eto-view/EtoViewUtils.ts
  packages/web/app/test-e2e/eto/InvestWithNEur.spec.e2e.ts
  packages/web/app/test-e2e/utils/index.ts
Labels: QA

#3573 Fix wrong image imports
  packages/web/app/components/eto/public-view/Cover.tsx
  packages/web/app/components/modals/wallet-access/AccessWalletModal.tsx
  packages/web/app/components/shared/HiResImage.tsx
  packages/web/app/components/shared/ResponsiveImage.stories.tsx
  packages/web/app/components/shared/ResponsiveImage.tsx
  packages/web/app/components/shared/SlidePerson.tsx
  packages/web/health-check-sha.json
Labels: TECH

#3570 Make utils filenames consistent across codebase
  packages/web/app/components/dashboard/my-portfolio/my-portfolio-widget/IncomingPayoutPending.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentProgress.tsx
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/InvestmentStatus/InvestmentProgress.tsx
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/Whitelist/WhitelistProgress.tsx
  packages/web/app/components/eto/public-view/Individuals.tsx
  packages/web/app/components/eto/shared/EtoViewUtils.ts
  packages/web/app/components/eto/utils.ts
  packages/web/app/components/modals/bank-transfer-flow/verify/BankTransferVerifyAgreement.stories.tsx
  packages/web/app/components/modals/tx-sender/investor-refund/RefundDetails.tsx
  packages/web/app/components/modals/tx-sender/shared/TxError.stories.tsx
  packages/web/app/components/modals/tx-sender/shared/TxSuccess.stories.tsx
  packages/web/app/components/modals/tx-sender/unlock-wallet-flow/UnlockWalletTransactionDetails.tsx
  packages/web/app/components/modals/tx-sender/withdraw-flow/withdraw/Withdraw.stories.tsx
  packages/web/app/components/portfolio/utils.ts
  packages/web/app/components/shared/Date.tsx
  packages/web/app/components/shared/Money.unsafe.tsx
  packages/web/app/components/shared/formatters/utils.spec.ts
  packages/web/app/components/wallet/wallet-balance/UnlockedETHWallet.tsx
  packages/web/app/components/wallet/wallet-balance/UnlockedNEURWallet.tsx
  packages/web/app/lib/web3/Web3Adapter.ts
  packages/web/app/lib/web3/Web3Manager/Web3Manager.ts
  packages/web/app/lib/web3/browser-wallet/BrowserWallet.ts
  packages/web/app/lib/web3/ledger-wallet/ledgerUtils.ts
  packages/web/app/lib/web3/light-wallet/LightWalletUtils.ts
  packages/web/app/modules/auth/constants.ts
  packages/web/app/modules/eto/constants.ts
  packages/web/app/modules/investment-flow/sagas.ts
  packages/web/app/modules/investor-portfolio/__tests__/selectors.spec.ts
  packages/web/app/modules/investor-portfolio/sagas.ts
  packages/web/app/modules/investor-portfolio/selectors.ts
  packages/web/app/modules/investor-portfolio/utils.ts
  packages/web/app/modules/tx-history/constants.ts
  packages/web/app/modules/tx/transactions/investment/selectors.spec.ts
  packages/web/app/modules/tx/transactions/investment/selectors.ts
  packages/web/app/modules/tx/transactions/redeem/saga.ts
  packages/web/app/modules/tx/validator/withdraw/sagas.ts
  packages/web/app/modules/web3/utils.ts
  packages/web/app/test-e2e/investor-dashboard/LightWalletInvestorDashboard.spec.e2e.io.ts
  packages/web/app/test-e2e/portfolio/Portfolio.spec.e2e.io.ts
  packages/web/app/test-e2e/utils/userHelpers.ts
  packages/web/app/utils/AsyncIntervalScheduler.ts
  packages/web/app/utils/DateUtils.spec.ts
  packages/web/app/utils/DateUtils.ts
  packages/web/app/utils/JWTUtils.spec.ts
  packages/web/app/utils/MoneyUtils.ts
  packages/web/app/utils/NumberUtils.spec.ts
  packages/web/app/utils/NumberUtils.ts
  packages/web/app/utils/PromiseUtils.spec.ts
  packages/web/app/utils/PromiseUtils.ts
  packages/web/package.json
Labels: TECH

#3569 #3486 Add conditional copy for whitelisted investor
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/EtoCardStatusManager.tsx
  packages/web/intl/locales/en-en.json
Labels: QA

#3574 #3549 Fix wallet address width
  packages/web/app/components/modals/DepositEthModal.module.scss
Labels: QA

#3579 date display improvements in set start date widget
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.tsx
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.tsx
  packages/web/app/components/modals/tx-sender/eto-flow/SetDateDetails.tsx
  packages/web/app/components/shared/TimeLeft.unsafe.tsx
  packages/web/app/config/constants.ts
  packages/web/app/modules/bookbuilding-flow/utils.ts
  packages/web/app/modules/eto-flow/selectors.ts
  packages/web/app/modules/eto-flow/utils.ts
  packages/web/app/test-e2e/eto-registration/SetEtoStartDate.spec.e2e.ts
  packages/web/intl/locales/en-en.json
Labels: Bug, QA

#3601 #3586 hide ISHA from non kyc users
  packages/web/app/components/eto/EtoIssuerView.tsx
  packages/web/app/components/eto/EtoNomineeView.tsx
  packages/web/app/components/eto/EtoPublicView.tsx
  packages/web/app/components/eto/EtoPublicViewByContractId.tsx
  packages/web/app/components/eto/public-view/DocumentsWidget.stories.tsx
  packages/web/app/components/eto/public-view/DocumentsWidget.tsx
  packages/web/app/components/eto/public-view/EtoInvestmentTermsWidget.stories.tsx
  packages/web/app/components/eto/public-view/EtoInvestmentTermsWidget.tsx
  packages/web/app/components/eto/shared/ETOState.tsx
  packages/web/app/components/eto/shared/EtoView.stories.tsx
  packages/web/app/components/eto/shared/EtoView.tsx
  packages/web/app/components/issuer-dashboard/dashboardStep/DashboardStep.tsx
  packages/web/app/lib/api/eto/EtoFileUtils.ts
  packages/web/app/modules/eto-documents/sagas.ts
  packages/web/app/modules/eto-documents/utils.ts
  packages/web/app/test-e2e/eto-registration/EtoPresaleStep.spec.e2e.ts
  packages/web/app/test-e2e/eto-registration/EtoPublicSaleStep.spec.e2e.ts
  packages/web/app/test-e2e/eto-registration/EtoRegistrationUtils.ts
  packages/web/app/test-e2e/eto-view/ISHADocuments.spec.e2e.io.ts
  packages/web/app/test-e2e/eto/Campaigning.spec.e2e.ts
  packages/web/test/fixtures.ts
Labels: QA

#3590 #3556 non icbm wallet shown for whitelisting
  packages/web/app/components/modals/tx-sender/investment-flow/Investment.tsx
  packages/web/app/components/modals/tx-sender/investment-flow/InvestmentTypeSelector.tsx
  packages/web/app/modules/investment-flow/sagas.ts
  packages/web/app/modules/investor-portfolio/sagas.ts
  packages/web/app/modules/investor-portfolio/selectors.ts
  packages/web/app/test-e2e/eto/InvestStartUpgradeFlow.spec.e2e.ts
  packages/web/app/test-e2e/eto/InvestWithUpgradedWalletEther.spec.e2e.ts
  packages/web/app/test-e2e/eto/utils.ts
Labels: Bug, QA

#3575 #3004 Automatically update email on verify in different tab
  packages/web/app/modules/auth/user/sagas.ts
  packages/web/app/test-e2e/settings/VerifyEmailWidget.spec.e2e.io.ts
  packages/web/app/test-e2e/utils/index.ts
  packages/web/app/test-e2e/utils/userHelpers.ts
Labels: QA

#3605 #3585 Fix whitelisting stats before presale
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.tsx
Labels: QA

#3614 #3593 investment step quick fixes
  packages/web/app/components/modals/tx-sender/investment-flow/Investment.module.scss
  packages/web/app/components/modals/tx-sender/investment-flow/Investment.stories.tsx
  packages/web/app/components/modals/tx-sender/investment-flow/Investment.tsx
  packages/web/app/components/modals/tx-sender/investment-flow/utils.tsx
  packages/web/intl/locales/en-en.json
Labels: QA

#3613 #3597 Add fundraising statistics and presale time counter to ETO Dashboard
  packages/web/app/components/issuer-dashboard/ETOFundraisingStatistics.module.scss
  packages/web/app/components/issuer-dashboard/ETOFundraisingStatistics.stories.tsx
  packages/web/app/components/issuer-dashboard/ETOFundraisingStatistics.tsx
  packages/web/app/components/issuer-dashboard/ETOPresaleCounterWidget.module.scss
  packages/web/app/components/issuer-dashboard/ETOPresaleCounterWidget.stories.tsx
  packages/web/app/components/issuer-dashboard/ETOPresaleCounterWidget.tsx
  packages/web/app/components/issuer-dashboard/EtoDashboard.tsx
  packages/web/app/components/shared/dashboard-widget/DashboardWidget.tsx
  packages/web/app/test-e2e/eto-registration/EtoPresaleStep.spec.e2e.ts
  packages/web/app/test-e2e/eto-registration/EtoPublicSaleStep.spec.e2e.ts
  packages/web/intl/locales/en-en.json
Labels: QA

#3610 #3584 Link bank account copy changes
  packages/web/intl/locales/en-en.json
Labels: QA

#3530 #3170 Improve refund flow
  packages/web/app/components/modals/tx-sender/investor-refund/RefundDetails.tsx
  packages/web/app/components/modals/tx-sender/investor-refund/RefundSummary.stories.tsx
  packages/web/app/components/modals/tx-sender/investor-refund/RefundSummary.tsx
  packages/web/app/components/modals/tx-sender/shared/TxGoToAction.tsx
  packages/web/app/components/modals/tx-sender/shared/TxSuccess.tsx
  packages/web/app/modules/tx/transactions/refund/saga.ts
  packages/web/app/modules/tx/transactions/refund/types.ts
  packages/web/app/test-e2e/eto/Refund.spec.e2e.ts
  packages/web/app/test-e2e/utils/index.ts
  packages/web/health-check-sha.json
  packages/web/intl/locales/en-en.json
Labels: QA

#3640 Rename convertToBigInt to convertToUlps for consistency
  packages/web/app/components/modals/bank-transfer-flow/verify/BankTransferVerifyAgreement.stories.tsx
  packages/web/app/components/modals/tx-sender/investment-flow/InvestmentPriceInfo.tsx
  packages/web/app/components/modals/tx-sender/shared/TxError.stories.tsx
  packages/web/app/components/modals/tx-sender/shared/TxSuccess.stories.tsx
  packages/web/app/components/modals/tx-sender/withdraw-flow/withdraw/Withdraw.stories.tsx
  packages/web/app/components/portfolio/utils.ts
  packages/web/app/components/shared/formatters/utils.ts
  packages/web/app/modules/eto/sagas.ts
  packages/web/app/modules/investment-flow/sagas.ts
  packages/web/app/modules/investor-portfolio/__tests__/selectors.spec.ts
  packages/web/app/modules/investor-portfolio/sagas.ts
  packages/web/app/modules/investor-portfolio/utils.ts
  packages/web/app/modules/tx/transactions/investment/selectors.spec.ts
  packages/web/app/modules/tx/transactions/investment/selectors.ts
  packages/web/app/modules/tx/transactions/redeem/saga.ts
  packages/web/app/modules/tx/validator/withdraw/sagas.ts
  packages/web/app/modules/web3/utils.ts
  packages/web/app/test-e2e/investor-dashboard/LightWalletInvestorDashboard.spec.e2e.io.ts
  packages/web/app/test-e2e/portfolio/Portfolio.spec.e2e.io.ts
  packages/web/app/utils/NumberUtils.spec.ts
  packages/web/app/utils/NumberUtils.ts
Labels: TECH

#3623 #3622 Fix document download button icon underline
  packages/web/app/components/eto/public-view/DocumentsWidget.tsx
  packages/web/app/components/eto/public-view/EtoInvestmentTermsWidget.tsx
  packages/web/app/components/eto/public-view/MarketingDocumentsWidget.tsx
  packages/web/app/components/issuer-dashboard/bookBuildingWidget/BookBuildingWidget.tsx
  packages/web/app/components/modals/download-token-agreements-modal/DownloadTokenAgreementModal.tsx
  packages/web/app/components/modals/icbm-wallet-balance-modal/BalanceModal.tsx
  packages/web/app/components/modals/tx-sender/investment-flow/Summary.tsx
  packages/web/app/components/modals/tx-sender/nominee/sign-agreement/SignAgreementSummary.tsx
  packages/web/app/components/modals/tx-sender/upgrade-flow/Summary.unsafe.tsx
  packages/web/app/components/modals/tx-sender/user-claim/Summary.tsx
  packages/web/app/components/shared/DocumentLink.module.scss
  packages/web/app/components/shared/DocumentLink.stories.tsx
  packages/web/app/components/shared/DocumentLink.tsx
  packages/web/app/components/shared/SingleColDocumentWidget.tsx
  packages/web/app/components/shared/buttons/Button.module.scss
  packages/web/app/components/shared/buttons/Button.tsx
Labels: QA

#3635 Cleans up transactions sagas folder
  packages/web/app/components/modals/tx-sender/shared/TxPending.tsx
  packages/web/app/modules/eto/sagas.ts
  packages/web/app/modules/tx/monitor/actions.ts
  packages/web/app/modules/tx/monitor/sagas.ts
  packages/web/app/modules/tx/transactions/actions.ts
  packages/web/app/modules/tx/transactions/claim/sagas.ts
  packages/web/app/modules/tx/transactions/eto-flow/sagas.ts
  packages/web/app/modules/tx/transactions/investment/sagas.ts
  packages/web/app/modules/tx/transactions/nominee/sign-agreement/sagas.ts
  packages/web/app/modules/tx/transactions/payout/accept/saga.ts
  packages/web/app/modules/tx/transactions/payout/redistribute/saga.ts
  packages/web/app/modules/tx/transactions/payout/sagas.ts
  packages/web/app/modules/tx/transactions/redeem/sagas.ts
  packages/web/app/modules/tx/transactions/refund/sagas.ts
  packages/web/app/modules/tx/transactions/sagas.ts
  packages/web/app/modules/tx/transactions/unlock/sagas.ts
  packages/web/app/modules/tx/transactions/upgrade/sagas.ts
  packages/web/app/modules/tx/transactions/withdraw/sagas.ts
Labels: TECH

#3641 Fix my neu marks widget jumping while loading payouts
  packages/web/app/components/dashboard/my-portfolio/MyPortfolioWidget.module.scss
  packages/web/app/components/dashboard/my-portfolio/MyPortfolioWidget.tsx
Labels: QA

#3632 Cleanup for #3597
  packages/web/app/components/issuer-dashboard/ETOFundraisingStatistics.stories.tsx
  packages/web/app/components/issuer-dashboard/ETOFundraisingStatistics.tsx
  packages/web/app/components/issuer-dashboard/ETOPresaleCounterWidget.module.scss
  packages/web/app/components/issuer-dashboard/ETOPresaleCounterWidget.tsx
  packages/web/app/components/issuer-dashboard/EtoDashboard.tsx
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.module.scss
  packages/web/app/components/issuer-dashboard/chooseEtoStartDateWidget/ChooseEtoStartDateWidget.tsx
  packages/web/app/components/shared/TimeLeftWithUTC.module.scss
  packages/web/app/components/shared/TimeLeftWithUTC.stories.tsx
  packages/web/app/components/shared/TimeLeftWithUTC.tsx
  packages/web/app/test-e2e/eto-registration/SetEtoStartDate.spec.e2e.ts
  packages/web/health-check-sha.json
  packages/web/intl/locales/en-en.json
Labels: TECH

#3648 #3631 Add loading indicator to ico monitor frame
  packages/web/app/components/eto/shared/EtoViewFundraisingStatistics.tsx
  packages/web/app/config/.env.commit
  packages/web/app/config/.env.common
  packages/web/app/config/.env.example
Labels: QA

#3665 Fix mobile metamask signing flow
  packages/web/app/utils/PromiseUtils.spec.ts
  packages/web/app/utils/PromiseUtils.ts
Labels: QA
