Repository Neufund/platform-frontend, pull requests merged in 2019-07, with the labels that each got.

#3153 #2756 add rich text editor
  .circleci/config.yml
  app/components/eto/shared/EtoView.tsx
  app/components/layouts/LayoutRegisterLogin.tsx
  app/components/shared/Field.module.scss
  app/components/shared/Field.spec.tsx
  app/components/shared/Field.tsx
  app/components/shared/SanitizedHtml.spec.tsx
  app/components/shared/SanitizedHtml.stories.tsx
  app/components/shared/SanitizedHtml.tsx
  app/components/shared/forms/Form.ts
  app/components/shared/forms/fields/FormFieldBoolean.tsx
  app/components/shared/forms/fields/FormFieldCheckboxGroup.tsx
  app/components/shared/forms/fields/FormTextArea.tsx
  app/components/shared/forms/fields/utils.unsafe.tsx
  app/components/shared/forms/index.tsx
  app/components/shared/forms/layouts/CheckboxLayout.stories.tsx
  app/components/shared/forms/layouts/CheckboxLayout.tsx
  app/components/shared/forms/layouts/RichTextAreaLayout.module.scss
  app/components/shared/forms/layouts/RichTextAreaLayout.stories.tsx
  app/components/shared/forms/layouts/RichTextAreaLayout.tsx
  app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  app/lib/yup-ts.ts
  app/styles/elements/ul-ol.scss
  app/styles/elements/ul.scss
  app/styles/overrides.scss
  app/test-e2e/eto-registration/EtoCompanyInformationFieldValidation.spec.e2e.io.ts
  app/test-e2e/eto-registration/EtoCompanyInformationRichTextEditor.spec.e2e.io.ts
  app/test-e2e/eto-registration/fixtures.ts
  app/test-e2e/eto-view/EtoViewForInvestor.spec.e2e.io.ts
  app/test-e2e/utils/forms.ts
  app/test-e2e/utils/navigation.ts
  app/test-e2e/utils/selectors.ts
  app/utils/yupUtils.ts
  cypress.json
  health-check-sha.json
  package.json
  test/setupTests.ts
  typings/modules.d.ts
  yarn.lock
Labels: QA

#3175 #3106 - Fix redeem fee calculation
  app/components/modals/tx-sender/redeem/BankTransferRedeemInit.tsx
  app/components/modals/tx-sender/redeem/CalculatedFee.tsx
  app/modules/bank-transfer-flow/actions.ts
  app/modules/bank-transfer-flow/reducer.ts
  app/modules/bank-transfer-flow/selectors.ts
  app/test-e2e/bank-transfer/RedeemNEUR.spec.e2e.io.ts
Labels: QA

#3177 #2821 Transacitons history list
  app/components/dashboard/my-portfolio/MyNeuWidget.tsx
  app/components/eto/shared/DashboardHeading.tsx
  app/components/modals/tx-sender/redeem/BankTransferRedeemInit.tsx
  app/components/shared/Heading.tsx
  app/components/shared/MoneySuiteWidget.module.scss
  app/components/shared/MoneySuiteWidget.tsx
  app/components/shared/TransactionData.module.scss
  app/components/shared/TransactionData.stories.tsx
  app/components/shared/TransactionData.tsx
  app/components/shared/formatters/Money.module.scss
  app/components/shared/formatters/Money.tsx
  app/components/shared/formatters/MoneyRange.tsx
  app/components/shared/formatters/utils.ts
  app/components/shared/table/NewTable.module.scss
  app/components/shared/table/NewTable.stories.tsx
  app/components/shared/table/NewTable.tsx
  app/components/translatedMessages/messages.tsx
  app/components/wallet/transaction-list/TransactionList.module.scss
  app/components/wallet/transaction-list/TransactionList.unsafe.tsx
  app/components/wallet/transactions-history/TransactionName.tsx
  app/components/wallet/transactions-history/TransactionsHistory.module.scss
  app/components/wallet/transactions-history/TransactionsHistory.tsx
  app/components/wallet/views/start/Start.tsx
  app/di/setupBindings.ts
  app/di/symbols.ts
  app/lib/api/ImmutableStorageApi.ts
  app/lib/api/analytics-api/AnalyticsApi.ts
  app/lib/api/analytics-api/interfaces.ts
  app/lib/api/client/IHttpClient.ts
  app/lib/api/eto/EtoApi.ts
  app/modules/actions.ts
  app/modules/contracts/sagas.ts
  app/modules/eto/constants.ts
  app/modules/eto/sagas.ts
  app/modules/reducer.ts
  app/modules/sagas.ts
  app/modules/sagasUtils.ts
  app/modules/tx-history/actions.ts
  app/modules/tx-history/constants.ts
  app/modules/tx-history/reducer.ts
  app/modules/tx-history/sagas.ts
  app/modules/tx-history/selectors.ts
  app/modules/tx-history/types.ts
  app/modules/tx-history/utils.ts
  app/test-e2e/eto-registration/EtoCompanyInformationRichTextEditor.spec.e2e.io.ts
  app/test-e2e/utils/forms.ts
  health-check-sha.json
  intl/locales/en-en.json
  webpack/proxy-urls.js
Labels: QA

#3186 #3169 choose document download based on eto stage
  app/components/eto/public-view/EtoInvestmentTermsWidget.tsx
  app/test-e2e/kyc/KYCFlowIndividualIDnow.spec.e2e.io.ts
  health-check-sha.json
Labels: QA

#3198 Hide transactions history under env flag NF_TRANSACTIONS_HISTORY_VISIBLE
  app/components/wallet/views/start/Start.tsx
  app/config/.env.common
  app/config/.env.example
Labels: TECH

#3200 Fix dead code elimination
  .circleci/config.yml
  app/components/AppRouter.tsx
  app/components/portfolio/utils.ts
  app/components/settings/backup-seed/PrivateKeyDisplay.tsx
  app/components/shared/DatePicker.tsx
  app/components/shared/Toast.tsx
  app/components/shared/links/ExternalLink.tsx
  app/config/.env.common
  app/config/.env.example
  app/config/constants.ts
  app/modules/immutable-file/sagas.ts
  app/modules/immutable-file/utils.ts
  app/modules/investor-portfolio/utils.ts
  app/utils/englishMnemonics.ts
  patches/bitcore-mnemonic+8.3.3.patch
  typings/modules.d.ts
Labels: TECH

#3197 #3190 Fix platform landing page
  app/components/dashboard/Dashboard.tsx
  app/components/documents/Documents.tsx
  app/components/edge-cases/MigrationFromLink.tsx
  app/components/eto/EtoDashboard.tsx
  app/components/eto/EtoIssuerView.tsx
  app/components/eto/EtoPublicView.tsx
  app/components/eto/EtoPublicViewByContractId.tsx
  app/components/eto/registration/Start.tsx
  app/components/eto/shared/routing/RedirectToEtoById.tsx
  app/components/eto/shared/routing/RedirectToEtoLink.tsx
  app/components/kyc/Kyc.tsx
  app/components/landing/Landing.module.scss
  app/components/landing/Landing.tsx
  app/components/landing/LandingEto.tsx
  app/components/layouts/Content.module.scss
  app/components/layouts/Content.tsx
  app/components/layouts/Layout.stories.tsx
  app/components/layouts/Layout.tsx
  app/components/layouts/menus/MyAccountMenu.module.scss
  app/components/layouts/menus/MyAccountMenu.tsx
  app/components/portfolio/Portfolio.tsx
  app/components/settings/Settings.tsx
  app/components/settings/backup-seed/BackupSeed.tsx
  app/components/shared/errorBoundary/ErrorBoundaryLayout.tsx
  app/components/wallet-selector/WalletSelector.tsx
  app/components/wallet-selector/wallet-recover/WalletRecoverMain.tsx
  app/components/wallet/Wallet.tsx
Labels: QA

#3193 #3019 eto overview layout fix
  app/components/eto/EtoDashboard.tsx
  app/components/eto/EtoIssuerView.tsx
  app/components/eto/EtoPublicView.tsx
  app/components/eto/EtoPublicViewByContractId.tsx
  app/components/eto/EtoWidgetView.tsx
  app/components/eto/overview/EtoOverviewStatus/CampaigningWidget/CampaigningActivatedWidget.tsx
  app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.module.scss
  app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.stories.tsx
  app/components/eto/overview/EtoOverviewStatus/EtoOverviewStatus.tsx
  app/components/eto/overview/EtoOverviewStatus/EtoStats.tsx
  app/components/eto/overview/EtoOverviewStatus/EtoStatusManager.tsx
  app/components/eto/overview/EtoOverviewStatus/EtoTitle.tsx
  app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentWidget.stories.tsx
  app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentWidget.tsx
  app/components/eto/overview/EtoOverviewStatus/RegisterNowWidget.tsx
  app/components/eto/overview/EtoOverviewStatus/TagsWidget.stories.tsx
  app/components/eto/overview/EtoOverviewStatus/TagsWidget.tsx
  app/components/eto/overview/EtoOverviewThumbnail/EtoOverviewThumbnail.tsx
  app/components/eto/public-view/CoverBanner.tsx
  app/components/eto/shared/ETOState.module.scss
  app/components/eto/shared/ETOState.tsx
  app/components/eto/shared/EtoView.stories.tsx
  app/components/eto/shared/EtoView.tsx
  app/components/portfolio/PortfolioPastInvestments.tsx
  app/components/portfolio/PortfolioReservedAssets.tsx
  app/components/shared/Tag.unsafe.tsx
  app/test-e2e/eto-registration/EtoRegistrationUtils.ts
  health-check-sha.json
  intl/locales/en-en.json
Labels: QA

#3215 Revert "#3126 - Redesign withdraw flow"
  app/components/dashboard/my-portfolio/MyNeuWidget.tsx
  app/components/landing/Landing.module.scss
  app/components/modals/tx-sender/TxDetails.unsafe.tsx
  app/components/modals/tx-sender/shared/DataRow.module.scss
  app/components/modals/tx-sender/shared/DataRow.stories.tsx
  app/components/modals/tx-sender/shared/DataRow.tsx
  app/components/modals/tx-sender/shared/TxError.stories.tsx
  app/components/modals/tx-sender/shared/TxPending.stories.tsx
  app/components/modals/tx-sender/shared/TxPending.tsx
  app/components/modals/tx-sender/shared/TxSuccess.stories.tsx
  app/components/modals/tx-sender/types.ts
  app/components/modals/tx-sender/withdraw-flow/Pending.stories.tsx
  app/components/modals/tx-sender/withdraw-flow/Pending.tsx
  app/components/modals/tx-sender/withdraw-flow/Success.stories.tsx
  app/components/modals/tx-sender/withdraw-flow/Success.tsx
  app/components/modals/tx-sender/withdraw-flow/Summary.stories.tsx
  app/components/modals/tx-sender/withdraw-flow/Summary.tsx
  app/components/modals/tx-sender/withdraw-flow/Withdraw.module.scss
  app/components/modals/tx-sender/withdraw-flow/Withdraw.stories.tsx
  app/components/modals/tx-sender/withdraw-flow/Withdraw.unsafe.tsx
  app/components/modals/tx-sender/withdraw-flow/WithdrawTransactionDetails.tsx
  app/components/shared/MaskedNumberInput.tsx
  app/components/shared/MoneySuiteWidget.module.scss
  app/components/shared/MoneySuiteWidget.tsx
  app/components/shared/TransactionData.module.scss
  app/components/shared/TransactionData.stories.tsx
  app/components/shared/TransactionData.tsx
  app/components/shared/buttons/Button.module.scss
  app/components/shared/buttons/Button.stories.tsx
  app/components/shared/buttons/Button.tsx
  app/components/shared/forms/fields/FormFieldError.module.scss
  app/components/shared/forms/fields/FormStyles.module.scss
  app/components/shared/forms/layouts/InputLayout.tsx
  app/components/wallet/transactions-history/TransactionsHistory.tsx
  app/lib/web3/Web3Adapter.ts
  app/modules/sagasUtils.ts
  app/modules/tx/sender/actions.ts
  app/modules/tx/sender/reducer.ts
  app/modules/tx/sender/selectors.ts
  app/modules/tx/transactions/withdraw/sagas.ts
  app/modules/tx/transactions/withdraw/types.ts
  app/modules/tx/types.ts
  app/modules/tx/utils.ts
  app/modules/tx/validator/sagas.ts
  app/styles/variables/colors.scss
  app/test-e2e/pending-transactions/utils.ts
  app/test-e2e/wallets/WalletWithdraw.spec.e2e.ts
  health-check-sha.json
  intl/locales/en-en.json
Labels: QA

#3189 #2821 TX history modals step 1
  app/components/shared/forms/fields/FormFieldColorful.unsafe.tsx
  app/components/shared/hooks/useButtonRole.spec.tsx
  app/components/shared/hooks/useButtonRole.ts
  app/components/shared/table/NewTable.module.scss
  app/components/shared/table/NewTable.stories.tsx
  app/components/shared/table/NewTable.tsx
  app/components/wallet/transactions-history/TransactionDetailsModal.tsx
  app/components/wallet/transactions-history/TransactionsHistory.module.scss
  app/components/wallet/transactions-history/TransactionsHistory.tsx
  app/modules/tx-history/actions.ts
  app/modules/tx-history/sagas.ts
  app/modules/tx-history/selectors.ts
  app/types.d.ts
  app/utils/enums/keys.enum.ts
Labels: QA

#3208 #3204 nominee account registration and login
  app/components/AppRouter.tsx
  app/components/appRoutes.ts
  app/components/landing/LandingEto.tsx
  app/components/layouts/header/Header.tsx
  app/components/layouts/menus/MenuAuthorized.tsx
  app/components/layouts/menus/MenuData.tsx
  app/components/nominee-dashboard/NomineeDashboard.tsx
  app/components/shared/routing/OnlyAuthorizedRoute.tsx
  app/components/shared/routing/SecretProtected.tsx
  app/components/wallet-selector/WalletSelector.tsx
  app/components/wallet-selector/wallet-recover/help/LoginHelp.tsx
  app/components/wallet-selector/walletRouterHelpers.ts
  app/config/.env.common
  app/lib/api/users/interfaces.ts
  app/modules/auth/jwt/sagas.ts
  app/modules/routing/actions.ts
  app/modules/wallet-selector/selectors.ts
  app/test-e2e/nominee-flow/NomineeFlow.spec.e2e.io.ts
  app/test-e2e/register/LightWalletETOLogin.spec.e2e.io.ts
  app/test-e2e/routing/AuthenticationRouting.spec.e2e.io.ts
  app/test-e2e/utils/assertions.ts
  app/test-e2e/utils/index.ts
  intl/locales/en-en.json
Labels: QA

#3226 Refactors ETO Public View
  app/components/eto/constants.tsx
  app/components/eto/public-view/CompanyDescription.tsx
  app/components/eto/public-view/DocumentsWidget.tsx
  app/components/eto/public-view/ETOTimeline.module.scss
  app/components/eto/public-view/ETOTimeline.tsx
  app/components/eto/public-view/EtoAccordionElements.tsx
  app/components/eto/public-view/Individuals.tsx
  app/components/eto/public-view/LegalInformationWidget.tsx
  app/components/eto/public-view/MarketingDocumentsWidget.tsx
  app/components/eto/public-view/PublicView.module.scss
  app/components/eto/shared/EtoView.tsx
  app/components/shared/Accordion.tsx
  intl/locales/en-en.json
Labels: QA, Requires Product Review

#3218 #2890 tx history transfer modal
  app/components/modals/tx-sender/eto-flow/SetDateSummary.unsafe.tsx
  app/components/modals/tx-sender/investment-flow/Success.tsx
  app/components/modals/tx-sender/shared/DataRow.module.scss
  app/components/modals/tx-sender/shared/DataRow.stories.tsx
  app/components/modals/tx-sender/shared/DataRow.tsx
  app/components/shared/AccountAddress.tsx
  app/components/shared/MoneySuiteWidget.module.scss
  app/components/shared/MoneySuiteWidget.stories.tsx
  app/components/shared/MoneySuiteWidget.tsx
  app/components/shared/Navigation.tsx
  app/components/shared/TransactionData.module.scss
  app/components/shared/TransactionData.stories.tsx
  app/components/shared/TransactionData.tsx
  app/components/shared/icons/CurrencyIcon.tsx
  app/components/shared/links/EtherscanLink.tsx
  app/components/shared/table/NewTable.module.scss
  app/components/shared/table/NewTable.tsx
  app/components/wallet-selector/ledger/WalletLedgerChooserTableAdvanced.tsx
  app/components/wallet/transactions-history/TransactionDetailsModal.module.scss
  app/components/wallet/transactions-history/TransactionDetailsModal.tsx
  app/components/wallet/transactions-history/TransactionsHistory.module.scss
  app/components/wallet/transactions-history/TransactionsHistory.tsx
  app/components/wallet/transactions-history/transaction-modal-content/BasicTransactionDetails.tsx
  app/components/wallet/transactions-history/transaction-modal-content/EtoRefundTransactionDetails.tsx
  app/components/wallet/transactions-history/transaction-modal-content/EtoTokensClaimTransactionDetails.tsx
  app/components/wallet/transactions-history/transaction-modal-content/NEurDestroyTransactionDetails.tsx
  app/components/wallet/transactions-history/transaction-modal-content/NEurPurchaseTransactionDetails.tsx
  app/components/wallet/transactions-history/transaction-modal-content/PayoutTransactionDetails.tsx
  app/components/wallet/transactions-history/transaction-modal-content/RedistributePayoutTransactionDetails.tsx
  app/components/wallet/transactions-history/transaction-modal-content/TransferTransactionDetails.tsx
  app/lib/api/analytics-api/AnalyticsApi.ts
  app/lib/api/analytics-api/interfaces.ts
  app/modules/shared/tokenPrice/selectors.ts
  app/modules/terms-of-service-modal/sagas.ts
  app/modules/tx-history/actions.ts
  app/modules/tx-history/reducer.ts
  app/modules/tx-history/sagas.ts
  app/modules/tx-history/types.ts
  app/modules/tx-history/utils.ts
  app/styles/variables/colors.scss
  app/types.d.ts
  intl/locales/en-en.json
Labels: QA

#3231 #1689 Add react node to yup
  app/components/eto/registration/pages/EtoTerms.tsx
  app/components/modals/bank-transfer-flow/shared/BankTransferAgreement.tsx
  app/components/modals/tx-sender/redeem/BankTransferRedeemInit.tsx
  app/components/modals/tx-sender/user-claim/SummaryForm.unsafe.tsx
  app/components/modals/tx-sender/withdraw-flow/Withdraw.unsafe.tsx
  app/components/translatedMessages/yupLocales.sideEffect.tsx
  app/components/wallet-selector/light/Login/LoginWithEmailLightWallet.unsafe.tsx
  app/components/wallet-selector/light/Register/RegisterLightWallet.unsafe.tsx
  app/lib/api/FileStorage.interfaces.ts
  app/lib/api/GasApi.ts
  app/lib/api/ImmutableStorage.interfaces.ts
  app/lib/api/KycApi.interfaces.ts
  app/lib/api/analytics-api/interfaces.ts
  app/lib/api/client/IHttpClient.ts
  app/lib/api/client/JsonHttpClient.ts
  app/lib/api/eto/EtoApi.interfaces.unsafe.ts
  app/lib/api/eto/EtoPledgeApi.interfaces.unsafe.ts
  app/lib/api/eto/EtoProductsApi.interfaces.ts
  app/lib/api/users/interfaces.ts
  app/lib/api/util/schemaHelpers.unsafe.ts
  app/lib/web3/Web3Adapter.ts
  app/lib/yup-ts.spec.ts
  app/lib/yup-ts.unsafe.tsx
  app/utils/ScrollToTop.unsafe.tsx
  intl/locales/en-en.json
  typings/yup.d.ts
Labels: TECH

#3235 Improve rich text editor usability/accessibility
  app/components/shared/forms/Form.ts
  app/components/shared/forms/fields/FormFieldLabel.tsx
  app/components/shared/forms/layouts/RichTextAreaLayout.tsx
  app/test-e2e/eto-registration/EtoCompanyInformationFieldValidation.spec.e2e.io.ts
  app/test-e2e/eto-registration/EtoCompanyInformationRichTextEditor.spec.e2e.io.ts
  app/test-e2e/utils/forms.ts
  app/test-e2e/utils/selectors.ts
  health-check-sha.json
Labels: TECH

#3233 Fix no payouts spacing
  app/components/portfolio/AssetPortfolio.tsx
Labels: QA

#3247 #2711 - Fix go to wallet button on issuer dashboard
  app/components/eto/dashboard/signInvestmentAgreementWidget/UploadInvestmentAgreementWidget.stories.tsx
  app/components/eto/dashboard/signInvestmentAgreementWidget/UploadInvestmentAgreementWidget.unsafe.tsx
  health-check-sha.json
Labels: QA
