Repository Neufund/platform-frontend, pull requests merged in 2020-01, with the labels that each got.

#3788 ETO update thumbnail designs
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/EtoCardStatusManager.tsx
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/EtoOverviewThumbnail.module.scss
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/InvestmentStatus/InvestmentStatus.module.scss
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/Whitelist/WhitelistProgress.module.scss
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/Whitelist/WhitelistProgress.tsx
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/Whitelist/WhitelistStatus.module.scss
  packages/web/app/components/eto/overview/EtoOverviewThumbnail/Whitelist/WhitelistStatus.tsx
Labels: QA

#3855 Cleanup for #3744
  packages/web/app/components/eto/overview/EtoOverviewStatus/EtoStats.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentStatusWidget.tsx
  packages/web/app/components/eto/overview/EtoOverviewStatus/InvestmentWidget/InvestmentTarget.tsx
  packages/web/app/components/eto/overview/InvestmentProgress.tsx
  packages/web/app/components/eto/overview/InvestmentProgressPercentage.tsx
  packages/web/app/components/eto/public-view/EtoInvestmentTermsWidget.module.scss
  packages/web/app/components/eto/public-view/EtoInvestmentTermsWidget.tsx
  packages/web/app/components/eto/public-view/InvestmentAmount.tsx
  packages/web/app/components/layouts/FullscreenProgressLayout.tsx
  packages/web/app/components/shared/Entry.module.scss
  packages/web/app/components/shared/Entry.stories.tsx
  packages/web/app/components/shared/Entry.tsx
  packages/web/app/components/shared/ProgressBarSimple.stories.tsx
  packages/web/app/components/shared/ProgressBarSimple.tsx
  packages/web/app/lib/api/eto/EtoUtils.ts
  packages/web/app/modules/eto/utils.spec.ts
  packages/web/app/modules/eto/utils.ts
  packages/web/app/utils/NumberUtils.spec.ts
  packages/web/app/utils/NumberUtils.ts
  packages/web/health-check-sha.json
Labels: TECH

#3880 Enforce node version check
  .circleci/config.yml
  README.md
  package.json
  packages/web/app/test-e2e/eto-view/ETOFoundersQuote.spec.e2e.io.ts
  packages/web/app/test-e2e/eto/InvestWithRegularEther.spec.e2e.ts
  packages/web/app/test-e2e/neur/RedeemNEUR.spec.e2e.io.ts
  packages/web/app/test-e2e/pending-transactions/PendingTransactionNetworkErrorsRecovering.spec.e2e.io.ts
  packages/web/app/test-e2e/pending-transactions/SupportForPendingTransactionsDuringTxFlow.spec.e2e.io.ts
  packages/web/test/integrationTestUtils.unsafe.tsx
Labels: TECH

#3914 Fix investment type styles shift
  packages/web/app/components/modals/tx-sender/investment-flow/InvestmentTypeSelector.module.scss
Labels: Blocker, Visual Fix

#3917 Fix portfolio token icon size
  packages/web/app/components/portfolio/AssetPortfolio.tsx
Labels: Blocker

#3878 Do not refresh JWT after inactivity logout
  packages/web/app/modules/auth/jwt/sagas.ts
  packages/web/app/test-e2e/eto-registration/SetEtoStartDate.spec.e2e.ts
  packages/web/app/test-e2e/eto-view/ETOFoundersQuote.spec.e2e.io.ts
  packages/web/app/test-e2e/general-app/AutoLoginLogoutActions.spec.e2e.io.ts
  packages/web/app/test-e2e/general-app/JWTEscalationAndRefreshing.spec.e2e.io.ts
  packages/web/app/test-e2e/general-app/utils.ts
  packages/web/app/test-e2e/investor-dashboard/LightWalletInvestorDashboard.spec.e2e.io.ts
  packages/web/app/test-e2e/pending-transactions/SupportForPendingTransactionsDuringTxFlow.spec.e2e.io.ts
  packages/web/app/test-e2e/utils/userHelpers.ts
  packages/web/cypress/support/commands.js
  packages/web/cypress/typings/cypress.d.ts
  packages/web/health-check-sha.json
Labels: Bug, QA

#3904 Fix recovery flow starts pooling
  packages/web/app/modules/auth/user/external/sagas.ts
  packages/web/app/modules/wallet-selector/light-wizard/sagas.ts
Labels: TECH

#3890 [All devs approval required] Developer workflow document
  docs/developer-workflow.md
  packages/web/health-check-sha.json
Labels: Documentation

#3932 #3308 Fix claimed token not showing in assets
  packages/web/app/modules/eto/sagas.ts
  packages/web/app/modules/tx/sender/actions.ts
  packages/web/app/modules/tx/transactions/claim/sagas.ts
  packages/web/app/test-e2e/kyc/KYCFlowSupportedInstandIdProviders.spec.e2e.io.ts
  packages/web/health-check-sha.json
Labels: QA

#3959 Redux DevTools Action Blacklist
  packages/web/app/index.tsx
Labels: TECH

#3961 Changes to ETO View
  .circleci/config.yml
  packages/web/app/components/eto/public-view/CoverBanner.tsx
  packages/web/app/components/eto/public-view/Disclaimer.module.scss
  packages/web/app/components/eto/public-view/Disclaimer.tsx
  packages/web/app/components/eto/shared/EtoView.tsx
  packages/web/app/test-e2e/portfolio/Portfolio.spec.e2e.io.ts
  packages/web/health-check-sha.json
  packages/web/intl/locales/en-en.json
Labels: QA

#3931 #3920 Create nds text input
  packages/web/app/components/shared/inputs/Field.stories.tsx
  packages/web/app/components/shared/inputs/Field.tsx
  packages/web/app/components/shared/inputs/InputBase.module.scss
  packages/web/app/components/shared/inputs/InputBase.stories.tsx
  packages/web/app/components/shared/inputs/InputBase.tsx
  packages/web/app/components/shared/inputs/InputDescription.module.scss
  packages/web/app/components/shared/inputs/InputDescription.stories.tsx
  packages/web/app/components/shared/inputs/InputDescription.tsx
  packages/web/app/components/shared/inputs/InputError.module.scss
  packages/web/app/components/shared/inputs/InputError.stories.tsx
  packages/web/app/components/shared/inputs/InputError.tsx
  packages/web/app/components/shared/inputs/LabelBase.module.scss
  packages/web/app/components/shared/inputs/LabelBase.stories.tsx
  packages/web/app/components/shared/inputs/LabelBase.tsx
  packages/web/app/components/shared/inputs/TextInput.module.scss
  packages/web/app/components/shared/inputs/TextInput.stories.tsx
  packages/web/app/components/shared/inputs/TextInput.tsx
  packages/web/app/styles/mixins/typography.scss
Labels: QA

#3964 #3963 Adds new product type
  packages/web/app/components/eto/registration/pages/etoTermsUtils.tsx
  packages/web/app/lib/api/eto/EtoProductsApi.interfaces.ts
  packages/web/intl/locales/en-en.json
Labels: QA

#3886 KYC upload all files that are dropped
  packages/web/app/components/kyc/business/BeneficialOwner.unsafe.tsx
  packages/web/app/components/kyc/business/BusinessData.unsafe.tsx
  packages/web/app/components/kyc/business/LegalRepresentative.unsafe.tsx
  packages/web/app/components/kyc/personal/AdditionalUpload.tsx
  packages/web/app/components/kyc/personal/Address.tsx
  packages/web/app/components/kyc/personal/Start.tsx
  packages/web/app/components/kyc/personal/Upload.tsx
  packages/web/app/components/kyc/shared/AddDocuments.tsx
  packages/web/app/components/kyc/utils.ts
  packages/web/app/components/shared/MultiFileUpload.stories.tsx
  packages/web/app/components/shared/MultiFileUpload.tsx
  packages/web/app/modules/kyc/reducer.ts
  packages/web/app/modules/kyc/selectors.ts
  packages/web/app/modules/kyc/utils.spec.ts
  packages/web/app/modules/kyc/utils.ts
  packages/web/app/test-e2e/eto-registration/EtoCompanyInformationRichTextEditor.spec.e2e.io.ts
  packages/web/app/test-e2e/kyc/KYCFlowCorporationManual.spec.e2e.io.ts
  packages/web/app/test-e2e/kyc/fixtures.ts
  packages/web/app/test-e2e/pending-transactions/SupportForPendingTransactionsDuringTxFlow.spec.e2e.io.ts
  packages/web/app/test-e2e/utils/forms.ts
  packages/web/cypress/support/commands.js
  packages/web/cypress/typings/cypress.d.ts
Labels: QA

#3924 Dmitriy noa/3269 await submitting form until all files where saved correctly
  docs/react-guidelines.md
  packages/web/@types/ckeditor__ckeditor5-react/index.d.ts
  packages/web/app/components/eto/registration/pages/AllForms.stories.tsx
  packages/web/app/components/eto/registration/pages/EtoEquityTokenInfo.tsx
  packages/web/app/components/eto/registration/pages/EtoPitch/EtoRegistrationPitch.tsx
  packages/web/app/components/eto/registration/pages/EtoPitch/connectEtoRegistrationPitch.ts
  packages/web/app/components/eto/registration/pages/EtoVotingRights/connectEtoVotingRightsForm.ts
  packages/web/app/components/shared/forms/fields/FormSingleFileUpload.tsx
  packages/web/app/components/shared/forms/fields/FormTextArea.tsx
  packages/web/app/components/shared/forms/layouts/RichTextAreaLayout.tsx
  packages/web/app/lib/api/file-storage/RichTextEditorUploadAdapter.ts
  packages/web/app/modules/eto-flow/actions.ts
  packages/web/app/modules/eto-flow/reducer.ts
  packages/web/app/test-e2e/eto-registration/EtoCompanyInformationRichTextEditor.spec.e2e.io.ts
  packages/web/cypress/fixtures/example_big.jpg
  packages/web/intl/locales/en-en.json
Labels: QA
